### ISSUE TITLE
Minor security considerations reported by Bandit

### ISSUE THREAD

**Issue by raratiru** [grantjenks/python-diskcache#100]
I have run [Bandit](https://github.com/PyCQA/bandit) over python-diskcache and reported some security considerations of Low(4) or Medium(2) severity:

The headlines of the issues are the following:

> * Issue: [B101:assert_used] Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
> * Issue: [B110:try_except_pass] Try, Except, Pass detected.
> * Issue: [B301:blacklist] Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue. [Medium]
> * Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
> * Issue: [B403:blacklist] Consider possible security implications associated with cPickle module.
> * Issue: [B608:hardcoded_sql_expressions] Possible SQL injection vector through string-based query construction. [Mdium Severity]

I understand that the reported lines are most probably consciously written this way, but nevertheless I attach the full report just in case the code quality can be improved further.

 [bandit_report.txt](https://github.com/grantjenks/python-diskcache/files/2814093/bandit_report.txt)

**Comment by grantjenks** [comment]
I reviewed the issues identified by Bandit. I don't believe any of these warrant changes to the code.

**Comment by raratiru** [comment]
All right, thank you for verifying.
