### ISSUE TITLE
No folder cleanup on deque pop()

### ISSUE THREAD

**Issue by grintor** [grantjenks/python-diskcache#103]
I have an application that was using python's collections.deque and making heavy use of it's maxlen=x parameter. I switched to python-diskcache's Deque which doesn't have support for maxlen, so I ended up just doing a .popleft() when the len() is too high on each append(). The problem is, that now I end up with a folder with literally hundreds of thousands of empty folders in it. I think this would grow to millions (billions?) at some point if the app ran long enough. I have a script that's iterating through them all periodically trying to delete empty folders and avoid race conditions of a folder that has only just been created and doesn't yet have data in it. It's messy... So I hope you can improve this so that .popleft() will delete not only the data, but also its folder too.

**Comment by grantjenks** [comment]
When a value is stored on the filesystem, a random hexadecimal name is generated for it. The first two characters are a folder and the second two characters are a subfolder. This folder/subfolder pair is created when the file is written to disk and it is left on the disk when the file is later deleted. There should be no more than 256 folders and no more than 256 subfolders in each of those folders. If you observe more than 256 folders or subfolders then it's a bug and I'd like to fix it.

Note that these folders and subfolders will be reused. They are not added endlessly. Disk cache will not create more 256 * 256 or 65,536 folders.

The folder/subfolder structure serves a purpose. If all the files were stored in a single directory, say 1,000,000 files in a single directory, then the filesystem may struggle simply to open a file (some file systems have to do a big scan to find the file). By dividing the files by folders and subfolders, filesystem operations remain quick and speedy. There is a size vs. speed tradeoff here. Folders typically require less than 1KB of space so for 65,536 folders the size is ~65MB which for a 1TB hard drive is less than 0.01%.

**Comment by grantjenks** [comment]
Beware that if you're using the deque concurrent to deleting folders/subfolders then you've introduced a race condition whereby diskcache may try to write a value to a directory that's just been deleted.

There's also a ``check()`` method on the underlying cache which can be called with ``fix=True`` which will remove the empty directories. The `check` method is intended for testing and post-mortem analysis. While `check` is running, there can be no reads/writes to the underlying cache.

**Comment by grintor** [comment]
Ah, I see. I has assumed that it was unlimited. Thank you for the clarification. I saw it grow to tens of thousands to folders, not hundreds of thousands as I first thought, my mistake. I suppose that's ok then. Thank you for the insight.

**Comment by SoundsSerious** [comment]
> When a value is stored on the filesystem, a random hexadecimal name is generated for it. The first two characters are a folder and the second two characters are a subfolder. This folder/subfolder pair is created when the file is written to disk and it is left on the disk when the file is later deleted. There should be no more than 256 folders and no more than 256 subfolders in each of those folders. If you observe more than 256 folders or subfolders then it's a bug and I'd like to fix it.
> 
> Note that these folders and subfolders will be reused. They are not added endlessly. Disk cache will not create more 256 * 256 or 65,536 folders.
> 
> The folder/subfolder structure serves a purpose. If all the files were stored in a single directory, say 1,000,000 files in a single directory, then the filesystem may struggle simply to open a file (some file systems have to do a big scan to find the file). By dividing the files by folders and subfolders, filesystem operations remain quick and speedy. There is a size vs. speed tradeoff here. Folders typically require less than 1KB of space so for 65,536 folders the size is ~65MB which for a 1TB hard drive is less than 0.01%.

@grantjenks This is really good to know! I've been relying more on diskcache for python but i'm struggling a bit with mutliprocess performance, i had been wondering about the methdology for the folder system

**Comment by Hsinfu** [comment]
> When a value is stored on the filesystem, a random hexadecimal name is generated for it. The first two characters are a folder and the second two characters are a subfolder. This folder/subfolder pair is created when the file is written to disk and it is left on the disk when the file is later deleted. There should be no more than 256 folders and no more than 256 subfolders in each of those folders. If you observe more than 256 folders or subfolders then it's a bug and I'd like to fix it.
> 
> Note that these folders and subfolders will be reused. They are not added endlessly. Disk cache will not create more 256 * 256 or 65,536 folders.
> 
> The folder/subfolder structure serves a purpose. If all the files were stored in a single directory, say 1,000,000 files in a single directory, then the filesystem may struggle simply to open a file (some file systems have to do a big scan to find the file). By dividing the files by folders and subfolders, filesystem operations remain quick and speedy. There is a size vs. speed tradeoff here. Folders typically require less than 1KB of space so for 65,536 folders the size is ~65MB which for a 1TB hard drive is less than 0.01%.
 
The minimum size of folders depends on the block size of filesystem.
For ext4, default block size is 4KiB, which means the minimum size of a folder is 4KiB -> we need 256 MiB.

```sh
# check block size
sudo tune2fs -l /dev/sda1 | grep -i 'block size' 
```
