### ISSUE TITLE
Python 3.8 collections deprecation warning

### ISSUE THREAD

**Issue by raratiru** [grantjenks/python-diskcache#107]
From the [docs](https://docs.python.org/3.8/library/collections.html):

> Changed in version 3.3: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely.

Hence the deprecation message:

`python3.7/site-packages/diskcache/persistent.py:8-9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

**Comment by grantjenks** [comment]
Merged in master. Will deploy in next release.
