### ISSUE TITLE
Inconsistent performance

### ISSUE THREAD

**Issue by TheCodeSummoner** [grantjenks/python-diskcache#109]
**Issue**

It seems that the time required to write the data is very inconsistent when using `FanoutCache` and `DiskCache`. Precisely, I have tested the former cache with 8 shards by writing a single value to it every `0.1` seconds. Here are the results of the *maximum* time required to set that value.

```
new max delay 0.12468910217285156
new max delay 0.16456389427185059
new max delay 0.26326751708984375
new max delay 0.2762327194213867
new max delay 0.3211393356323242
new max delay 0.6004025936126709
```

As presented, the delay reaches up to `0.6` seconds which causes an overall lag of the application, and the inconsistency stays with more values to write and more frequent writes as well (up to 25 values every 0.03 seconds). Could you please advise what could be the potential cause of this and/or propose a solution?

I am trying to share a lot of data between different processes and modules in `Python`, however, I perform a very significant number of writes and reads throughout. Sadly, I am unaware of other solutions to easily sharing the data which do not involve fiddling with lower-level languages, but if you do know any more suitable tools to solve my issue - could you propose those as well?

**Comment by grantjenks** [comment]
Can you share your benchmarking code? I will see if I can reproduce.

**Comment by TheCodeSummoner** [comment]
I have prepared a simplified version for you:

```python
from time import time, sleep
from diskcache import FanoutCache

# Initialise the maximum delay reference
max_delay = 0

# Initialise the reference to current time
# Add a significant amount of time to ignore the first measurement due to other initialisations
current_time = time() + 100

# Initialise the Fanout Cache instance
data = FanoutCache('test', shards=8)


# Declare the function used to modify the data
def set_data(**kwargs):
    """

    Function used to modify the cache.

    :param kwargs: Key, value pairs of data to modify.

    """

    # Fetch the global variables
    global max_delay
    global current_time
    global data

    # Update the data with the given keyword arguments
    for key, value in kwargs.items():

        # Measure the time taken to update it for each item
        temp = time()
        dif = temp - current_time
        if dif > max_delay:
            max_delay = dif
            print("New max delay encountered: ", max_delay)
        current_time = temp

        # Update the data
        data[key] = value


# Initialise some test values
test_values = {str(key): value for key in range(25) for value in range(25)}

# Keep writing the data in 0.1 sec intervals
while True:
    sleep(0.1)
    set_data(**test_values)
```

Some example outputs:

```
New max delay encountered:  0.03626513481140137
New max delay encountered:  0.04390859603881836
New max delay encountered:  0.05416607856750488
New max delay encountered:  0.10073137283325195
New max delay encountered:  0.10075139999389648
New max delay encountered:  0.10080623626708984
New max delay encountered:  0.10190200805664062
New max delay encountered:  0.10193681716918945
New max delay encountered:  0.5416762828826904
```

```
New max delay encountered:  0.02889251708984375
New max delay encountered:  0.043881893157958984
New max delay encountered:  0.04402518272399902
New max delay encountered:  0.044837236404418945
New max delay encountered:  0.10077404975891113
New max delay encountered:  0.10112166404724121
New max delay encountered:  0.10174083709716797
New max delay encountered:  0.10176920890808105
New max delay encountered:  0.10177135467529297
New max delay encountered:  0.10184192657470703
New max delay encountered:  0.10198068618774414
New max delay encountered:  0.34280896186828613
New max delay encountered:  0.5068113803863525
```

**Comment by grantjenks** [comment]
Did you intend to include the `sleep(0.1)` in your measurement? All of your max values add 100ms to the FanoutCache set time. Also, your test values is `{str(num): num for num in range(25)}`. Here's my updated version of your benchmark:

```
"""Benchmark for Issue #109

"""

import time
import diskcache as dc


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--cache-dir', default='/tmp/test')
    parser.add_argument('--iterations', type=int, default=100)
    parser.add_argument('--sleep', type=float, default=0.1)
    parser.add_argument('--size', type=int, default=25)
    args = parser.parse_args()

    data = dc.FanoutCache(args.cache_dir)
    delays = []
    values = {str(num): num for num in range(args.size)}
    iterations = args.iterations

    for i in range(args.iterations):
        print(f'Iteration {i + 1}/{iterations}', end='\r')
        time.sleep(args.sleep)
        for key, value in values.items():
            start = time.monotonic_ns()
            data[key] = value
            stop = time.monotonic_ns()
            diff = stop - start
            delays.append(diff)

    # Discard warmup delays, first two iterations.
    del delays[:(len(values) * 2)]

    # Display performance.
    delays = sorted(delay / 1000 for delay in delays)  # Convert ns to us.
    print()
    print(f'Total #:  {len(delays)}')
    print(f'Min delay (us): {delays[0]:>8.3f}')
    print(f'50th %ile (us): {delays[int(len(delays) * 0.50)]:>8.3f}')
    print(f'90th %ile (us): {delays[int(len(delays) * 0.90)]:>8.3f}')
    print(f'99th %ile (us): {delays[int(len(delays) * 0.99)]:>8.3f}')
    print(f'Max delay (us): {delays[-1]:>8.3f}')


if __name__ == '__main__':
    main()
```

And the results:

```
Iteration 100/100
Total #:  2450
Min delay (us):  133.679
50th %ile (us):  233.804
90th %ile (us):  315.302
99th %ile (us):  609.577
Max delay (us): 5294.699
```

Which matches the timing data reported in the docs at http://www.grantjenks.com/docs/diskcache/cache-benchmarks.html#timing-data The FanoutCache with 8 shards has a Max/P99 ratio of 44x and pretty closely matches what is seen here.

What I can't see is the 500ms slowdown that you report. Perhaps it's our systems? I'm running on a MacBook Pro (2013) with an SSD.

**Comment by TheCodeSummoner** [comment]
Ah, apologies, I should've specified more precisely that it was simply the slowdown that was weird for me. The delay was simply there to match the first example output I have posted, and thank you for simplifying the dict comprehension, it was initially something else but I have simplified it and missed the easier representation.

I am using Python version 3.6.4 so monotonic_ns is not there for me yet. I will adjust the code as soon as possible.

**Comment by TheCodeSummoner** [comment]
I have double checked today and it turned out that I wasn't using SSD at all to store the cache, as I was running the scripts from my D drive, so naturally it was slower because of that. The performance is (as expected) really good once the cache is successfully stored on the C drive.

Apologies for the confusion :(
