### ISSUE TITLE
Allow multi-machine use?

### ISSUE THREAD

**Issue by johann-petrak** [grantjenks/python-diskcache#111]
Would be possible to allow usage of the diskcache via some sort of network connections (sockets, http, ..)? Or is there some library which could be easily used to wrap that functionality? 

So instead of specifying a file, one would have to specify e.g. a hostname/port except the first which would have to specify the location and binding address  port to start the server etc ..

**Comment by grantjenks** [comment]
A socket interface is beyond the scope of disk cache. Why not use Redis, Memcached, or a SQL database?

If you just need something quick, maybe the XML-RPC module in the standard library could get you there.

**Comment by johann-petrak** [comment]
The reason for my question is because after looking at many similar libraries, this one by far is the most convenient and easiest to use, no requirement to install redis or memcached etc. In fact, it implements a lot of the functionality that redis or memcache provide, but better: e.g. there is no deque in Redis. 

So unless sharding is required, for simpler situations, it would be perfect to use python-diskcache from multiple machines (while it is running on one machine and using only the resources there) at the same time for communication between distributed processes. The only thing needed for this would be a lightweight wrapper that uses some kind of zero-config network method to communicate between a client and the python-diskcache "server" running somewhere. 

I agree that this could just as well be a separate project, but since it is the only thing I miss for my own application I thought it may be worth a try to see what people think about this here, and as part of the project. Again my primary thought was that it could extend the extreme usability of the library for multiprocessing on a single machine to the same usability across machines.

**Comment by grantjenks** [comment]
Thanks for the kind words about the project!

I wonder if something could be built quickly out of ZeroRPC: https://github.com/0rpc/zerorpc-python look at the last example in the readme and you’ll see in just a few lines that you can expose a class’s methods over tcp sockets. Does that work for you?

Also, there are a number of projects that build data types atop Redis and there’s several methods there that support queuing. RQ: https://github.com/rq/rq for example seems very popular.

**Comment by grantjenks** [comment]
For zerorpc client code see: http://www.zerorpc.io/

I wish something with the simple API of zerorpc existed for the XML-RPC module.
