### ISSUE TITLE
diskcache+asyncio?

### ISSUE THREAD

**Issue by mayli** [grantjenks/python-diskcache#116]
So, if we replace the sqlite with https://github.com/jreese/aiosqlite, how hard to make an async version of python-diskcache?

**Comment by grantjenks** [comment]
I’m not sure. I think it would require extensive changes to the source base. Every sql statement would need to be awaited.

It may be easier to copy the design of aiosqlite and move all computation to a background thread. The aiosqlite package doesn’t really make interacting with SQLite asynchronous. It just moves the synchronous computation to a thread queue so the event loop can make progress with other tasks.

**Comment by mayli** [comment]
Got it! Thanks for the explanation.

**Comment by grantjenks** [comment]
No problem, thanks for asking! I think it would be worthwhile to add a section to the docs about how to do this so I'm going to reopen as a reminder.

The API in asyncio is https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools and here's a short example:

```
$ python -m IPython
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import diskcache as dc                                                                                        

In [2]: cache = dc.Cache('/tmp/cache')                                                                                

In [3]: import asyncio                                                                                                

In [4]: async def set(key, value): 
   ...:     loop = asyncio.get_running_loop() 
   ...:     result = await loop.run_in_executor(None, cache.set, key, value) 
   ...:     return result 
   ...:                                                                                                               

In [6]: asyncio.run(set('test-key', 'test-value'))                                                                    
Out[6]: True
```

**Comment by grantjenks** [comment]
I added a section to the docs in Caveats with example usage at dfad0aa

**Comment by nathanahtan** [comment]
I've been testing this and it seems using the executor is quite a bit slower than without.  Any insights into why this might be?

Thanks.

**Comment by grantjenks** [comment]
Try re-using an executor. The executor has to otherwise start threads and set() is pretty quick.

**Comment by nathanahtan** [comment]
Ok thanks.  As far as I know I'm only using the loop's default executor.  I see now that the difference diminishes with increasing calls to set(), so I guess it is some kind of initial overhead.  I'm not sure about thread lifetime within the executor either...maybe it has some continuous overhead there.

**Comment by geekscrapy** [comment]
> Try re-using an executor. The executor has to otherwise start threads and set() is pretty quick.

Do you have an example of this? What is the executor?

Thanks 👍
