### ISSUE TITLE
Caching limited to 1GB in total?

### ISSUE THREAD

**Issue by NikEyX** [grantjenks/python-diskcache#117]
Could it be that there is a disk size limit to the caching? I need to cache up to 50GB, but there seems to be a hard limit at ~1GB? Here is a replication:

```import numpy as np
import diskcache as dc
a = dc.Cache('/tmp/test')

for i in range(100000):
    a[i] = np.random.randn(1000, 1000)
    if i % 100 == 0:
        print(len(a))
```
resulting in:
```
1
101
131 <----- ?????
131
131
....
```

Checking the cache dir, it's exactly 1 GB big. Is there any way I can increase that?

**Comment by NikEyX** [comment]
ok using `cache.reset('cull_limit', 0)` made this work and it looks like there is a size_limit option as well. It would be great if you could add this to the readme, since it wasn't easy to find.

**Comment by grantjenks** [comment]
It’s discussed repeatedly in the tutorial and documented specifically at http://www.grantjenks.com/docs/diskcache/tutorial.html#settings
