### ISSUE TITLE
What has changed in version 4.0

### ISSUE THREAD

**Issue by jaap3** [grantjenks/python-diskcache#119]
I've been using DiskCache version 3.1.1 for a while and just saw that version 4.0 has been released. I cannot find a overview of the (potential backwards incompatible) changes, are there any or can I safely upgrade from 3 to 4?

**Comment by grantjenks** [comment]
I don’t think there are any major backwards incompatible changes. The version bump was for significant new features. There’s a short write up on python-announce-list at https://mail.python.org/archives/list/python-announce-list@python.org/thread/K4RJJH2BY3ALI2K32JZ7FY2VPZKRLS3P/
