### ISSUE TITLE
Add HDF to comparison?

### ISSUE THREAD

**Issue by flutefreak7** [grantjenks/python-diskcache#120]
As a novice engineering/data science user I'm more familiar with HDF5 than I am with databases. HDF can make very large hierarchical  datasets available and stream the data from disk into memory as needed. I've heard it's heavily used in places like particle accelerators and other large scale science projects. For another example, it's also what Matlab uses for their *.mat files in recent years. A similar file format, NetCDF, can also use HDF as it's backend.

Anyway, I'm curious how this compares to HDF. My guess is there might be scenarios where HDF is faster for certain types of indexed queries of big arrays (since that's what it's optimized for), but that this beats naive use of HDF. I wonder if the answer changes for a 1 GB vs 20 GB dataset.

**Comment by grantjenks** [comment]
I’d be curious too but I know little about HDF. You could try subclassing the diskcache.Disk data type to change the serialization layer.

Overall, I think diskcache is much more generic in its design and so quite different. My list of comparisons is not meant to be exhaustive. I tried to focus only on what was generally useful and popular.

If you create some benchmarks, then feel free to share in a pull request though I may not merge it.
