### ISSUE TITLE
Implementation in Flask and connection closing

### ISSUE THREAD

**Issue by jlorieau** [grantjenks/python-diskcache#121]
I'm trying to implement disk cache as an extension in Flask. On every request, Flask creates a new connection to the disk cache and closes it when the request is done. In profiling requests, I noticed that disk cache conducts about 85 execute commands on the sqllite3 connection when I create a new diskcache connection, and this takes about 7.9 ms on my server. Am I suppose to avoid closing the connection between requests? (i.e. the ``teardown`` method below gets called at the end of every request)

Thanks!

JL

Code below
```python
"""
Connections for diskcache
"""
import diskcache
from flask import current_app, _app_ctx_stack


class DiskCache(object):
    def __init__(self, app=None):
        self.app = app
        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        app.teardown_appcontext(self.teardown)

    def connect(self):
        return diskcache.Cache(current_app.config['DISKCACHE_LOCATION'])

    def teardown(self, exception):
        ctx = _app_ctx_stack.top
        if hasattr(ctx, 'diskcache'):
            ctx.diskcache.close()

    @property
    def connection(self):
        ctx = _app_ctx_stack.top
        if ctx is not None:
            if not hasattr(ctx, 'diskcache'):
                ctx.diskcache = self.connect()
            return ctx.diskcache


dc = DiskCache()
```

**Comment by grantjenks** [comment]
Yes, reuse the open cache if possible. You can also share it amongst multiple threads and it’s safe to fork the process. I would just make it a global or class attribute

**Comment by jlorieau** [comment]
ok thanks
