### ISSUE TITLE
Bug: 'least-recently-used' and 'least-recently-stored' can boot all data from db

### ISSUE THREAD

**Issue by bvasilev** [grantjenks/python-diskcache#122]
Both replacement policies can boot all data in the cache in certain circumstances. Below is one example. The results are the same with both policies.

```
from diskcache import Cache
import numpy as np

cache = Cache(eviction_policy='least-recently-used', size_limit=10**9)

print(list(cache.iterkeys())) # prints []
cache['ones'] = np.ones(10**8)
print(list(cache.iterkeys())) # prints ['ones']
cache['ones'] = np.zeros(10**8)
print(list(cache.iterkeys())) # prints [], should print ['zeros']
```

**Comment by grantjenks** [comment]
Looks like there’s a typo in your example as currently the ‘zeros’ key is never set. But assuming the second assignment causes culling, the behavior is expected. Change the [cull_limit setting](http://www.grantjenks.com/docs/diskcache/tutorial.html#settings) to control the number of items culled. The default value is ten. Lower values will cause culling more often. The cache is optimized for the case where items stored are much smaller (like << 1/100) than the total cache size.

**Comment by bvasilev** [comment]
There was a typo!
The actual example was:

```
from diskcache import Cache
import numpy as np

cache = Cache(eviction_policy='least-recently-used', size_limit=10**9)
print(list(cache.iterkeys())) # prints []

cache['ones'] = np.ones(10**8)
print(list(cache.iterkeys())) # prints ['ones']

cache['zeros'] = np.zeros(10**8)
print(list(cache.iterkeys())) # prints [], should print ['zeros']
```

So after the last assignment the cache is left completely empty.
It seems to me that the 'ones' should be culled, to make space for the 'zeros', but then the 'zeros' should be in the cache in the end?

**Comment by grantjenks** [comment]
I think the confusion is due to a misnomer. It doesn't delete items one-by-one up to the "limit." It selects up to "limit" items and deletes them. When you go beyond the size limit, it's going to try and delete ten items by default. Here's the code: https://github.com/grantjenks/python-diskcache/blob/master/diskcache/core.py#L868
