### ISSUE TITLE
Docs site is down

### ISSUE THREAD

**Issue by ABitMoreDepth** [grantjenks/python-diskcache#129]
Hi folks, came across this library recently and it looks really interesting, however when trying to browse the docs, I get a 404 error from Nginx, after being redirected away from http://www.grantjenks.com/docs/diskcache/ to https://www.kjxqz.com/docs/diskcache/

Is there any chance someone can poke the docs server back into life?

**Comment by grantjenks** [comment]
It’s working fine for me. Are you trying to access https? It’s only at http

**Comment by ABitMoreDepth** [comment]
You are correct, my work environment tries to force to use HTTPS and was failing in this instance.  The docs are fine from home.
