### ISSUE TITLE
Tutorial exampe by JSONDisk

### ISSUE THREAD

**Issue by svaite** [grantjenks/python-diskcache#130]
Hi.
I apologize right away for my broken English.
In [Disk tutorial](http://www.grantjenks.com/docs/diskcache/tutorial.html#tutorial-disk), when changing the **Cache** to the **Index**, writing and reading bypasses the JSONDisk class.
Was that planned? If so, why?
Thank you

**Comment by grantjenks** [comment]
I think that was not intended. Can you show me your code? How do you change from Cache to Index?

There is also an Index.fromcache method I think. That would support the JSON Disk.

**Comment by svaite** [comment]
This example does not compress values:
`test_cache = Index(cache_dir, disk=JSONDisk, disk_compress_level=6)`
But this works good:
`test_cache = Cache(cache_dir, disk=JSONDisk, disk_compress_level=6)`

**Comment by grantjenks** [comment]
Yes, of course. Index does not have the same signature as Cache. Check the API docs. The signature of Index is meant to match that of dict.

**Comment by svaite** [comment]
Good.
Last question: what is the practical use of the Index? 1-2 examples for more understanding.
And thank you for this cool project.

**Comment by grantjenks** [comment]
Index has nearly the same semantics as a dict but is persistent and accessible across threads and processes. There’s no server to setup. See how Index and Deque can be used to parallelize code here: http://www.grantjenks.com/docs/diskcache/case-study-web-crawler.html
