### ISSUE TITLE
Help with debugging an issue in diskcache sqlite3 connection

### ISSUE THREAD

**Issue by argaen** [grantjenks/python-diskcache#131]
Hello, I've spent I don't know how many hours already debugging an issue in one of our stacks where I'm trying to use this package. In one of the classes I'm doing the following:
```
self.cache = Cache(directory="/tmp/diskcache")
self.cache.set(key, value)
self.cache.get(key)
```
`self.cache.get` **always** returns **None**.

After some debugging I can say that the information is stored in the files and I can retrieve it using the `_disk` private attribute passing the correct parameters. What apparently is not working is the part of storing the data in sqlite3, more specifically the [_insert_row](https://github.com/grantjenks/python-diskcache/blob/0e273fb54f9bfec6a33e6be7cdf9a68f0ea2adaa/diskcache/core.py#L885) method. After it is being executed and the outer transact finished, the `Cache` table is still empty. However, if I grab the return of the `sql` command from the `_insert_rows` and execute a `commit` the data appears!

Also what I've tried is the following while in the middle of a breakpoint:
```
ipdb> from diskcache import Cache
ipdb> cache = Cache("/tmp/diskcache")
ipdb> cache.set("key", "value")
True
ipdb> cache.get("key")
ipdb> cache = Cache("/tmp/diskcache-1")
ipdb> cache.set("key", "value")
True
ipdb> cache.get("key")
'value'
```

`/tmp/diskcache` is the directory used originally in the process that doesn't work and as you can see, it still doesn't work if I initialize it manually in the debugger. However, if I use another path it works fine inside the debugger! 

I'm really confused on why the sql command is not working correctly and even more why its not raising an error? Any ideas of what it could be or what else I could check?

EDIT: Some further info. If I import sqlite3 module directly and work with it, I can insert items in the cache table under `/tmp/diskcache`

```
    119             self.cache.set("key", "value")
    120             conn = sqlite3.connect('/tmp/diskcache/cache.db')
    121             conn.cursor()
    122             conn.execute("insert into Cache values (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)")
    123             conn.commit()
    124             import ipdb; ipdb.set_trace()
--> 125             

[1]+  Stopped                 make run-dev
root@c5f8b84e358a:/user# sqlite3 /tmp/diskcache/cache.db
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> select * from Cache;
1|1|1|1.0|1.0|1.0|1|1|1|1|1|1
```

Thanks!

**Comment by grantjenks** [comment]
What’s your OS and where did you get your Python executable from? Is it Jython, Pypy, or did you install with pyenv? Macports?

Check the SQLite pragma settings. Seems like your connection is not running in autocommit mode.

Also try running the test suite: clone the repo then run “$ python setup.py test”

**Comment by argaen** [comment]
> What’s your OS and where did you get your Python executable from? Is it Jython, Pypy, or did you install with pyenv? Macports?

Sorry missed specifying the environment:

- python3.6 using python Docker image
- diskcache==4.1.0

> Check the SQLite pragma settings. Seems like your connection is not running in autocommit mode.

Hmmm but why would it work as expected when running as a standalone program? With a simple sscript functionality is as expected... That's what I don't understand. 

How do I check if its running with autocommit mode? what's the specific setting you would like me to check? Also do we need it? according to the line https://github.com/grantjenks/python-diskcache/blob/master/diskcache/core.py#L773 the commit is forced on each operation no?

> Also try running the test suite: clone the repo then run “$ python setup.py test”

Tried but got 
```
GLOB sdist-make: /tmp/python-diskcache/setup.py
ERROR: invocation failed (exit code 1), logfile: /tmp/python-diskcache/.tox/log/GLOB-0.log
================================================================ log start =================================================================
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/usr/local/lib/python3.6/distutils/core.py", line 16, in <module>
    from distutils.dist import Distribution
  File "/usr/local/lib/python3.6/distutils/dist.py", line 9, in <module>
    import re
  File "/usr/local/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

================================================================= log end ==================================================================
ERROR: FAIL could not package project - v = InvocationError('/usr/local/bin/python setup.py sdist --formats=zip --dist-dir /tmp/python-diskcache/.tox/dist', 1)
```

But as mentioned, behavior is the expected outside the app environment where I'm trying to integrate it 😕

**Comment by argaen** [comment]
If I patch the class as follows it solves the issue but it is far from ideal (coz I don't use `_transact` nor `_cull` anymore so I'm able to commit each insert I perform):

```
class PatchedCache(Cache):
    def set(self, key, value, expire=None, read=False, tag=None, retry=False):
        """Set `key` and `value` item in cache.
        When `read` is `True`, `value` should be a file-like object opened
        for reading in binary mode.
        Raises :exc:`Timeout` error when database timeout occurs and `retry` is
        `False` (default).
        :param key: key for item
        :param value: value for item
        :param float expire: seconds until item expires
            (default None, no expiry)
        :param bool read: read value as bytes from file (default False)
        :param str tag: text to associate with key (default None)
        :param bool retry: retry if database timeout occurs (default False)
        :return: True if item was set
        :raises Timeout: if database timeout occurs
        """
        sql = self._sql
        now = time.time()
        db_key, raw = self._disk.put(key)
        expire_time = None if expire is None else now + expire
        size, mode, filename, db_value = self._disk.store(value, read, key=key)
        columns = (expire_time, tag, size, mode, filename, db_value)

        rows = sql(
            'SELECT rowid, filename FROM Cache'
            ' WHERE key = ? AND raw = ?',
            (db_key, raw),
        ).fetchall()

        if rows:
            (rowid, old_filename), = rows
            self._row_update(rowid, now, columns)
        else:
            self._row_insert(db_key, raw, now, columns)

        return True

    def _row_insert(self, key, raw, now, columns):
        sql = self._sql
        expire_time, tag, size, mode, filename, value = columns
        command = sql('INSERT INTO Cache('
            ' key, raw, store_time, expire_time, access_time,'
            ' access_count, tag, size, mode, filename, value'
            ') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', (
                key,
                raw,
                now,         # store_time
                expire_time,
                now,         # access_time
                0,           # access_count
                tag,
                size,
                mode,
                filename,
                value,
            ),
        )
        try:
            command.connection.commit()
        except sqlite3.OperationalError:
            pass
```

Sorry that the issue is a bit abstract or maybe not related to the library per se, I'm hoping to reverse engineer the solution from the working changes I have plus your knowledge of the library.. :)

**Comment by grantjenks** [comment]
I’ve seen odd things like this before. If you search the bug tracker then you’ll find an odd concurrency bug that was due to different compilation settings. I’m wondering if something like that is happening here.

There have also been issues with pypy where commit() calls were needed but not for cpython. I’ve been paranoid before that commit() is explicitly needed in many more places throughout. But it’s hard to reproduce and not necessary for CPython.

One more idea: for pypy the issue was that finalizers on the connection would automatically commit. So depending on when gc occurred, commits would happen at unreliable times. Because CPython is mostly reference counted it’s likely less an issue.

**Comment by grantjenks** [comment]
If you could also dump all the pragma settings it would allow you to compare in both environments. Some compilation settings in SQLite change the semantics significantly. And when pragmas are set, they fail silently :(

**Comment by argaen** [comment]
> I’m wondering if something like that is happening here.

I'm installing with `pip install diskcache`

> If you could also dump all the pragma settings it would allow you to compare in both environments.

I think I didn't explain it very well sorry. The situations where it does and doesn't work are both undr the same exact environment (docker image). The only difference is that the cache I initialize in the app (Flask service) has this issue while if in the middle of a breakpoint (or even executing a script  in the same image) I instantiate a cache manually, that one works so I don't think it is an issue with my compilation of sqlite settings but more of a weird concurrency issue and maybe file handlers.

Note with the patched class I've written above it works fine (doing an explicit `commit`). But still don't know the reason and would prefer not to modify the code to run it in production :(

**Comment by argaen** [comment]
Huh... so setting `cull_limit` to 0 fixes this, no need for class changes... 🤔 Wondering why it is expiring the items that have been set if I'm not setting any expiration in the set method 🙃

**Comment by grantjenks** [comment]
Are they big values? They might be evicted immediately. When using shards the max size is divided amongst the shards.

**Comment by argaen** [comment]
Some of them can be up to the order of 20kb, 50kb or so (not optimal and something we can improve in this future). You think that's the issue? I'm not using Shards, I'm just using the Core cache

**Comment by grantjenks** [comment]
No, that’s not very big, assuming the cache default size is a gigabyte. But it sounds like the item is getting culled immediately. Is it expiring immediately? Try stepping through the cull method to see if it is deleted there.

**Comment by argaen** [comment]
We've set the cache size to 32MB. With `cull_limit=0` it works as expected but I don't know the reason yet... Will try to debug when I have some more time, thanks for your time!

**Comment by grantjenks** [comment]
Did you ever find the problem?

**Comment by argaen** [comment]
Hey @grantjenks! thanks for asking. No, I did debug a bit more but couldn't find anything meaningful so I left it as is. I'm closing in order to reduce noise :)
