### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by leepand** [grantjenks/python-diskcache#133]
great project, but there  sometimes shows "Too many open files" message

**Comment by grantjenks** [comment]
Can you share a script that reproduces the issue? I’ve not seen that before in Disk Cache.

**Comment by leepand** [comment]
thx for your quick response, this message just appears when I initialize instance(init=Cache(diff_ persistence_path)) in different pyfile , maybe this is the reason?

**Comment by grantjenks** [comment]
If you make a lot of instances then, yes. Every Cache instance opens a file and maintains a file handle. *nix systems have limits on the number of files that can be open at the same time. It typically ranges from a couple hundred to couple thousand files. The setting can be changed at the session or kernel level and is fairly arbitrary.

You could create a single cache and have it shared by many instances. The cache keys could then include the instance id to maintain separate namespaces.

If you know of another cache library that works around the OS limits then I’d be glad to take a look as to how.

**Comment by leepand** [comment]
thank you very much, I'll try it later.
