### ISSUE TITLE
age of Index() cache/entries?

### ISSUE THREAD

**Issue by sarnold** [grantjenks/python-diskcache#135]
Mainly I guess I'm somewhat confused about whether the Index() cache variant supports tags; I did see where the docs mention Dequeue and Index "never evict or expire items" so expire_time is obviously moot.  I don't get any errors setting tags for index items but I don't see any way to retrieve a tag.  Am I barking up the wrong tree here?

**Comment by sarnold** [comment]
Things were looking strange during testing before I removed some installed cruft; now I get the appropriate syntax errors using the above args with an Index() cache.  Sorry about the noise; is there a way to get the "age" of cache objects from an Index() or do I need to track that externally?  For now I'm just doing an explicit ``cache.clear()`` before getting "fresh" input data, but that seems a little brutal.

**Comment by grantjenks** [comment]
Index does not support tags. The api matches python’s dict datatype. You also cannot see the age of items in an Index. The api matches dict. You want a Cache. Use that and set the eviction policy to ‘none’: http://www.grantjenks.com/docs/diskcache/tutorial.html#eviction-policies

**Comment by sarnold** [comment]
Thanks, I made a cache wrapper for handling timestamps/aging (around the api interface that queries and loads the cache) and it seems to work well enough for now.  In this case it's partly my own fault for using my own keys instead of using prefix for specific item categories in the cache.  I plan to refactor things soon and test that assumption...
