### ISSUE TITLE
Removing cache after the process is finished

### ISSUE THREAD

**Issue by lucventurini** [grantjenks/python-diskcache#137]
Dear @grantjenks ,
many thanks for this project, I had been using hand-written SQLite caches in my programs but your solution looks much more performant and stable than anything ad-hoc.
I have one question, though - I do not see any automatic way of deleting the cache during the end of a program. This would leave the cache on disk, which can be unfeasible when e.g. having jobs on a cluster. This is also superfluous as the caches I am writing really only serve the purpose of shuffling data between processes within a same application and therefore are useless for any other process/program that might be executed before or after.

What is the best recommended solution for my use-case? Something like 

```
c = diskcache.Cache()
c.close()
import shutil
shutil.rmtree(c.directory)
```
for example?

Also, as an idea for development, would it be possible to add as optional behaviour the automatic removal of the cache folder when the connection ends? Something like

```
c = diskcache.Cache(remove_on_closing=True)
```

which would automatically remove the cache at the end.

Again many thanks for such an amazing product!

**Comment by grantjenks** [comment]
That’s correct. Use shutil.rmtree to delete the cache and all its data. Everything will be stored within the cache directory.

I Would rather not add the remove-on-closing functionality to diskcache itself. The feature can be easily implemented with the contextlib module in the standard library. Consider:

    @contextlib.contextmanager
    def rmtree_on_close():
        cache = Cache(...)
        yield cache
        cache.close()
        shutil.rmtree(cache.directory)

**Comment by lucventurini** [comment]
Dear @grantjenks , thank you for your clarification. I have manually added `rmtree` calls for the moment, I will consider looking into `contextlib` (thanks for the pointer!).

Kind regards
