### ISSUE TITLE
The cache filename schema is not very optimal for a default config

### ISSUE THREAD

**Issue by mayli** [grantjenks/python-diskcache#138]
The diskcache is using a [two-level subdir](https://github.com/grantjenks/python-diskcache/blob/1149e822c4a9b8bb8eaf27874c228100ddc380b1/diskcache/core.py#L327) to shard the cache value files into different directories.
With the default cache settings, the cache folder is going to have about 256*256=65536 folders. The default disk_min_file_size=32k and size_limit=1gb, we only have about 31250 files, that means we have 0.5 files per folder.

That matches the behavior I saw on a heavy used cache, resulting tons of empty folders but each folder only have few files, mostly just 1 file.

How about use the [levels](http://nginx.org/en/docs/http/ngx_http_proxy_module.html) from nginx, making it customizable or default to `1:2` or just `2`? The `1:2` approach only has 2048 folder with 16 files in each folder, the `2` will have even less folder and more balanced directory tree.
`1:2`: /data/nginx/cache/**c**/**29**/b7f54b2df7773722d382f4809d650**29c**
`2`: /data/nginx/cache/**9c**/b7f54b2df7773722d382f4809d6502**9c**

**Comment by grantjenks** [comment]
Does it matter to have a bunch of empty directories? The default size limit of 1GB makes it excessive but I know of installations with 1TB cached. When increasing the size, it's nice to not worry about other settings.

It's also possible to inherit from Disk and provide whatever customization is desired. The JSONDisk is an example.

**Comment by mayli** [comment]
Well, it's wasting the inodes when they are just empty. My assumption is that default values are good enough for normal usage, but it force me to write my own Disk class(which I already did) for the filename.
