### ISSUE TITLE
HTTPS website certificate error

### ISSUE THREAD

**Issue by jayvdb** [grantjenks/python-diskcache#141]
https://www.grantjenks.com/docs/diskcache/ shows a cert mismatch error as it is only valid for kjxqz.com & www.kjxqz.com

**Comment by grantjenks** [comment]
Use http.

**Comment by ssbarnea** [comment]
Considering that modern browser will soon refuse to use HTTP, I doubt that your recommendation can be seen practical. If SSL management is hard to setup and maintain, there are always alternatives like https://readthedocs.org/

**Comment by grantjenks** [comment]
Just to give an update here, https is coming to grantjenks.com. Likely in the next couple months.

**Comment by grantjenks** [comment]
Done! Docs now at https://grantjenks.com/docs/diskcache/
