### ISSUE TITLE
File instead of sql cache with jupyter

### ISSUE THREAD

**Issue by Slind14** [grantjenks/python-diskcache#147]
Hi there,

when using diskcache with jupyter it is creating a file cache while when using it with python directly it is using the sqlite backend. 

Is there any way to make sure that it is always using the same backend? Ideally the file one.

**Comment by grantjenks** [comment]
Depends on the size of the values. There’s nothing Jupyter-specific about the storage. Change the  disk_min_file_size setting to 0.

**Comment by grantjenks** [comment]
I’m also curious why the file-behavior is desirable here? The SQLite storage is usually faster for small values.

**Comment by Slind14** [comment]
hmm, this is interesting. We are using the exact same date and methods in both cases.

Even when the system keeps them in file cache?

**Comment by grantjenks** [comment]
What does "Even when the system keeps them in memory?" mean?

**Comment by Slind14** [comment]
https://www.thomas-krenn.com/en/wiki/Linux_Page_Cache_Basics

**Comment by grantjenks** [comment]
I see. Yes, SQLite will still be faster because it is memory-mapped into the process’s memory space and there’s less open/close overhead: https://www.sqlite.org/fasterthanfs.html

**Comment by Slind14** [comment]
Thanks
