### ISSUE TITLE
key not in Cache directly after setting it - how to debug?

### ISSUE THREAD

**Issue by jhmenke** [grantjenks/python-diskcache#149]
Situation:

I am inserting (or concatenating) pandas dataframes into a Cache:

```
if key in db and db[key] is not None:
    cur_df = db.pop(key)
    df = pd.concat((cur_df.loc[set(cur_df.index) - set(df.index)], df), sort=sort, copy=False).copy(deep=True)
assert len(df) > 0
db.set(key, df)  # alternatively db[key] = df
assert key in db
```

It works fine most of the time, but everytime at the same point in running my script, the last assert is False. It just inserted the new dataframe, but isn't accessible in the Cache. Then when i restart the script, all key or most existing keys are missing.

How can i go about debugging this? I am on Windows and only using a single thread to access the Cache.
Thanks!

**Comment by grantjenks** [comment]
Sounds like the key is getting evicted probably due to space constraints. Try using a diskcache.Index if you don’t want eviction or setting the eviction_policy to ‘none’

**Comment by grantjenks** [comment]
You could also set a breakpoint in Cache._cull and see where the key is getting deleted.

**Comment by jhmenke** [comment]
> Sounds like the key is getting evicted probably due to space constraints. Try using a diskcache.Index if you don’t want eviction or setting the eviction_policy to ‘none’

I think that's it, thanks! It was a datame being stored with - saved as a pickle file - takes up more than 1 GB of space weirdly, but that's a different issue.
