### ISSUE TITLE
Redirect docs

### ISSUE THREAD

**Issue by amakko** [grantjenks/python-diskcache#150]
Link
http://www.grantjenks.com/docs/diskcache/
redirect to
https://www.kjxqz.com/docs/diskcache/ 
and site not work
`404 Not Found
nginx/1.10.3 (Ubuntu)`

**Comment by grantjenks** [comment]
Don’t use https. Your browser is doing the redirect.

I’ve seen this a couple different places. Is https some kind of corporate policy thing?

**Comment by grantjenks** [comment]
Duplicate of #141
