### ISSUE TITLE
OverflowError: BLOB longer than INT_MAX bytes

### ISSUE THREAD

**Issue by jmrichardson** [grantjenks/python-diskcache#156]
Hi, I am working with  very large dataframes that is passed as an argument to a memoize function using diskcache.  I get the following error:

`OverflowError: BLOB longer than INT_MAX bytes`

Which I assume is because DC is limited by the maximum blob size it can store in its database for the argument key?  It seems that it is able to cache the large return dataframe but get the error when I send the large dataframe back as an argument:

```
# Each of the below functions are @cache.memoize()
trn, tst = kibot(f"data/kibot/minute/ibm.csv")   # trn is relatively small
trn = technical_analysis(trn)  # The resulting trn is very big
trn = clean(trn)  # This gives the error (trn does not grow in this function so should be cached fine)
```

I am wondering if the argument can be truncated to the INT_MAX bytes as a best effort?  

I hope this makes sense and appreciate any help

**Comment by grantjenks** [comment]
That's right. Default maximum blob size is 1,000,000,000 bytes as described in https://www.sqlite.org/limits.html

You can customize the behavior of keys using the "Disk" parameter: http://www.grantjenks.com/docs/diskcache/tutorial.html#disk Sounds like you want to truncate the key size to one billion bytes. See the reference docs: http://www.grantjenks.com/docs/diskcache/api.html#diskcache.Disk You'll need to override the put() method. I'm not sure you can define the get() method ... that'll break some things, like peekitem(), iterkeys(), maybe some others.

Another option would be to "hash" the parameter with md5() or something. That'll let you store a much smaller key. But it'll have the same problem as the truncation. It'll be unable to recover the keys in the cache.

**Comment by jmrichardson** [comment]
Thank you!
