### ISSUE TITLE
Want to use it as a simple database

### ISSUE THREAD

**Issue by jinserk** [grantjenks/python-diskcache#157]
I found this project during seeking a disk-backed simple database. Firstly I checked to use `shelve` but saw the benchmarks and tried to replace it to diskcache. I really appreciate this great work!

My questions are:
- To use the "cache" as a "database", is it enough to set `size_limit` sufficiently large and to set `cull_limit` to 0?
- What about the memory? If the cache `size_limit` is bigger than the memory size, how it handle the in-memory data? Or will it raise OOM?
- Is there any way to save the memory usage, while the culling disabled? I'd like to swap the in-memory data entities with on-disk entities if the memory is full. Is it possible?

Thank you again!

**Comment by grantjenks** [comment]
Use the "none" eviction policy as described in the docs: http://www.grantjenks.com/docs/diskcache/tutorial.html#eviction-policies

The default settings will use only 64 MB of memory, maximum. Anything larger will be paged out to disk.

**Comment by jinserk** [comment]
Thank you for prompt answer! By the way, can I ask one more question? What is the difference between the `cull_limit=0` and the `evection_policy=none` ?

**Comment by grantjenks** [comment]
See diskcache.Cache._cull

When the cull limit is zero, no keys are ever culled (even expired keys). When the eviction policy is none, keys may still expire, but will not be evicted by policy if the size limit is exceeded.

It’s possible to set the cull limit to zero to disable culling altogether. Some choose to do so for the fast-paths in their code and move culling to a Cron-like job.

**Comment by jinserk** [comment]
Then is there any way to prevent expiration?

**Comment by grantjenks** [comment]
Expiration always defaults to None in parameter lists.

If you want a simple database then the just use the Index and Deque data types. They were made exactly for your use case as persistent mapping and sequence data types.

http://www.grantjenks.com/docs/diskcache/tutorial.html#index

**Comment by jinserk** [comment]
Sounds great! Thank you very much!! :)
