### ISSUE TITLE
Populate python_requires setup.py field

### ISSUE THREAD

**Issue by markgras** [grantjenks/python-diskcache#160]
Per the official [PyPA docs](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires):

> If your project only runs on certain Python versions, setting the `python_requires` argument to the appropriate PEP 440 version specifier string will prevent pip from installing the project on other Python versions.

Currently, running `python2.7 -m pip install diskcache` fails because of Python 3 syntax in this package. Since `diskcache` now only supports Python 3.5 and up, I propose that this field be set to prevent such installation errors with future package releases. Acceptable values are `>=3.5` and `~=3.5` (which to use is up to you).

**Comment by grantjenks** [comment]
Thanks for that link.

I've published 5.0.3 with the correct metadata and yanked 5.0.0-5.0.2. Installing for Python 2 now grabs v4 as it should.
