### ISSUE TITLE
sqlite3.DatabaseError Database Disk image is malformed

### ISSUE THREAD

**Issue by kartikeyangupta** [grantjenks/python-diskcache#164]
I am trying to access Disk-cache concurrently which is shared between 2 hosts using NFS, due to which one of them is creating lock and the other host is not able to access the cache.
This makes cache totally incompatible for 1 host for any read/write operation.
Is there a work around for this

```
Traceback (most recent call last):
  File "./utils/checks.py", line 22, in health_disk_cache
    cache_conn = Cache(CACHE_LOCATION)
  File "/usr/local/lib/python3.6/site-packages/diskcache/core.py", line 528, in __init__
    sql(query, (key, value))
  File "/usr/local/lib/python3.6/site-packages/diskcache/core.py", line 693, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by grantjenks** [comment]
Nope. SQLite and NFS don't play nice with each other. See the Caveats section: http://www.grantjenks.com/docs/diskcache/tutorial.html#caveats

**Comment by kartikeyangupta** [comment]
Thanks for the Info
