### ISSUE TITLE
memoize not working in Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [grantjenks/python-diskcache#166]
Hi

I would like to be able to use DiskCache in my development process and maybe also in production. I'm developing analytics apps in [Panel](panel.holoviz.org) which is built on top of [Bokeh](https://bokeh.org/) which again runs on the [Tornado](server) server. C.f. my site [awesome-panel.org](https://awesome-panel.org).

Panel can be run with a development option that reloads the server when the code I work on is changed. To make the reload as fast as possible I would like to use DiskCache to cache dataframes and for example [HoloViews](http://holoviews.org/) plots.

To make the use as easy as possible I would like to use the `memoize` function on my functions. But I cannot get it working.

### Example

To run the below example you would need to `pip install hvplot pandas panel`.

```python
import time

import hvplot.pandas
import numpy as np
import pandas as pd
import panel as pn
import param

from diskcache import FanoutCache

EXPIRE = 5 * 60  # 5 minutes
CACHE_DIRECTORY = "cache"

# cache=pn.state.cache # Simple builtin dictionary cache
cache=FanoutCache(directory=CACHE_DIRECTORY)

@cache.memoize()
def _get_data(value):
    print("loading data", value)
    time.sleep(1)
    print("data loaded")
    return pd.DataFrame(np.random.randint(0, 100, size=(100, 4)), columns=list("ABCD"))

def _get_plot(dataframe):
    return dataframe.hvplot(x="A", y="B")


class MyApp(param.Parameterized):
    value = param.Integer(default=0, bounds=(0, 100))

    data = param.DataFrame()
    plot = param.Parameter()
    view = param.Parameter()

    def __init__(self, **params):
        super().__init__(**params)

        self.plot_panel = pn.pane.HoloViews()

        self.view = pn.Column(self.param.value, self.plot_panel)

        self._update_data()

    @param.depends("value", watch=True)
    def _update_data(self):
        self.data = _get_data(self.value)

    @param.depends("data", watch=True)
    def _update_plot(self):
        self.plot = _get_plot(self.data)

    @param.depends("plot", watch=True)
    def _update_plot_panel(self):
        self.plot_panel.object = self.plot


if __name__.startswith("bokeh"):
    pn.config.sizing_mode = "stretch_width"
    MyApp().view.servable()
if __name__=="__main__":
    for index in range(0,5):
        _get_data(index)
```

![image](https://user-images.githubusercontent.com/42288570/97788959-2648b480-1bbd-11eb-8fa9-c6d18b1f0c06.png)

### It works when I run it as a Python file

```bash
$ python 'scripts\test_diskcache.py'
loading data 0
data loaded
loading data 1
data loaded
loading data 2
data loaded
loading data 3
data loaded
loading data 4
data loaded
(.venv)
$ python 'scripts\test_diskcache.py'
(.venv)
```

### It does not work when I run the Panel application

```bash
$ python -m panel serve 'scripts\test_diskcache.py' --dev
2020-10-31 20:56:23,204 Starting Bokeh server version 2.2.3 (running on Tornado 6.0.4)
2020-10-31 20:56:23,205 User authentication hooks NOT provided (default user enabled)
2020-10-31 20:56:23,208 Bokeh app running at: http://localhost:5006/test_diskcache
2020-10-31 20:56:23,208 Starting Bokeh server with process id: 14216
```

If I open `http://localhost:5006/test_diskcache` and drag the slider from 0 to 5 I get.

```bash
loading data 0
data loaded
2020-10-31 20:57:40,001 WebSocket connection opened
2020-10-31 20:57:40,002 ServerConnection created
loading data 1
data loaded
loading data 2
data loaded
loading data 3
data loaded
loading data 4
data loaded
loading data 5
data loaded
```

If open `http://localhost:5006/test_diskcache` in a tab (new session) and drag the slider from 0 to 5 I get

```bash
loading data 0
data loaded
2020-10-31 20:59:29,567 WebSocket connection opened
2020-10-31 20:59:29,567 ServerConnection created
loading data 1
data loaded
loading data 2
data loaded
loading data 3
data loaded
loading data 4
data loaded
loading data 5
data loaded
```

All the `loading data` and `data loaded` statements shows that the cache is not used by the second session.

#### Question

My question is really how to get the `memoize` decorator working. I've tried to study the documentation without luck

#### This works but is cumbersome

If I replace the `_get_data` function with the below code. Then it works

```python
def _get_data(value):
    value_str= str(value)
    if value_str in cache:
        return cache[value_str]
    else:
        print("loading data", value)
        time.sleep(1)

        df = pd.DataFrame(np.random.randint(0, 100, size=(100, 4)), columns=list("ABCD"))
        cache[value_str] = df
        print("data loaded")
        return df
```

but requires more boiler plate code and time to design.

#### Additional Context

- Maybe this is related to the FR for coroutine/async support https://github.com/grantjenks/python-diskcache/issues/125
- I would like to tryout if combining with an in memory cache like lru_cache would work. See https://github.com/grantjenks/python-diskcache/issues/92. This might speed my development process even more up.

**Comment by grantjenks** [comment]
I use diskcache in Bokeh web applications and it works fine. The asyncio nature of Bokeh should not cause issues.

Common issues are either caching large values and getting surprise evictions or having the relative cache directory move working directories between invocations.

I don’t see an issue with the code as written. If you can create a reduced repro, I’m happy to try running it myself.

**Comment by MarcSkovMadsen** [comment]
Thanks @grantjenks . Here is a reduced repro.

```python
import time

import panel as pn
import param

from diskcache import FanoutCache

pn.config.sizing_mode = "stretch_width"

EXPIRE = 5 * 60  # 5 minutes
CACHE_DIRECTORY = "cache"

# cache=pn.state.cache # Simple builtin dictionary cache
cache = FanoutCache(directory=CACHE_DIRECTORY)


@cache.memoize()
def _get_data(value):
    print("loading data. Input: ", value)
    time.sleep(1)
    data = value * 2
    return data


class MyApp(param.Parameterized):
    value = param.Integer(default=0, bounds=(0, 10))
    data = param.Integer()

    def __init__(self, **params):
        super().__init__(**params)

        self.data_panel = pn.pane.Str()
        self.loading_spinner = pn.widgets.indicators.LoadingSpinner(
            width=25, height=25, sizing_mode="fixed"
        )

        self.view = pn.Column(
            self.loading_spinner, self.param.value, self.data_panel, max_width=500
        )

        self._update_data()

    @param.depends("value", watch=True)
    def _update_data(self):
        self.loading_spinner.value = True
        self.data_panel.object = f"Data: {_get_data(self.value)}"
        self.loading_spinner.value = False


if __name__.startswith("bokeh"):

    MyApp().view.servable()
```

![diskcache](https://user-images.githubusercontent.com/42288570/97795764-aea17680-1c0a-11eb-994a-01514678f21b.gif)

**Comment by MarcSkovMadsen** [comment]
FYI. I have started a discussion in the Panel community on best practices for caching with Panel. I have included the DiskCache example that works. See https://discourse.holoviz.org/t/discussion-on-best-practices-for-advanced-caching-please-join/1371.

**Comment by MarcSkovMadsen** [comment]
@grantjenks . I can see what the problem is.. In `core.py: 1850` the value of `base = (full_name(func),) if name is None else (name,)` is different for each session and restart of the server.

If I include a few `print` statements in the `decorator` function (see below) I see the following in my terminal

```bash

```
![image](https://user-images.githubusercontent.com/42288570/97957278-05de4d00-1dab-11eb-8ab3-b7a735b1f518.png)


### `decorator` with print statements

```python
 def decorator(func):
            "Decorator created by memoize() for callable `func`."
            base = (full_name(func),) if name is None else (name,)
            print("base", base)

            @ft.wraps(func)
            def wrapper(*args, **kwargs):
                "Wrapper for callable to cache arguments and return values."
                key = wrapper.__cache_key__(*args, **kwargs)
                print("wrapper key", key)
                result = self.get(key, default=ENOVAL, retry=True)

                if result is ENOVAL:
                    result = func(*args, **kwargs)
                    if expire is None or expire > 0:
                        self.set(key, result, expire, tag=tag, retry=True)

                return result

            def __cache_key__(*args, **kwargs):
                "Make key for cache given function arguments."
                return args_to_key(base, args, kwargs, typed)

            wrapper.__cache_key__ = __cache_key__
            return wrapper

        return decorator
```

**Comment by MarcSkovMadsen** [comment]
Below I will list a few workarounds to solve the problems.

### Run `panel serve` with `--dev` from a separate file.

Bokeh/ Panel only renames the `main` file.

For example a separate `app.py` file that looks like

```python
from issue_hvplot_pickle import MyApp

MyApp().view.servable()
```

Would work.

**Comment by MarcSkovMadsen** [comment]
A solution for `memoize` could be to replace the `bokeh_app_SESSION_ID` with `bokeh_app_` like below. That works. Would that be a solution @grantjenks?

An alternative for me is just to have my own implementation of the memoize function and share the workaround with the Panel community.

```python
def decorator(func):
            "Decorator created by memoize() for callable `func`."
            fname = full_name(func)
            if fname.startswith("bokeh_app_"):
                fname=("bokeh_app_")
            base = (fname,) if name is None else (name,)

            @ft.wraps(func)
            def wrapper(*args, **kwargs):
                "Wrapper for callable to cache arguments and return values."
                key = wrapper.__cache_key__(*args, **kwargs)
                print("wrapper key", key)
                result = self.get(key, default=ENOVAL, retry=True)

                if result is ENOVAL:
                    result = func(*args, **kwargs)
                    if expire is None or expire > 0:
                        self.set(key, result, expire, tag=tag, retry=True)

                return result

            def __cache_key__(*args, **kwargs):
                "Make key for cache given function arguments."
                return args_to_key(base, args, kwargs, typed)

            wrapper.__cache_key__ = __cache_key__
            return wrapper

        return decorator
```

**Comment by grantjenks** [comment]
Just set the “name” keyword argument in the decorator memoize() call, that’s what it’s made for.

**Comment by MarcSkovMadsen** [comment]
Thanks. I've closed the issue.
