### ISSUE TITLE
Support efficient data science development workflow by understanding if the implementation of a function has changed.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [grantjenks/python-diskcache#168]
[Streamlit](https://www.streamlit.io/) is a highly popular and trending framework for creating ML apps in Python. One of the super powers of Streamlit is very efficient caching. See https://docs.streamlit.io/en/stable/caching.html.

They also need it because they essentially has one callback that is called all the time. So all sub functions used by the main callback needs caching for the app to be fast.

The Streamlit caching is

- simple to use and understand.
- supports caching a really wide range of data engineering and data science objects.

The Streamlit server automatically reloads and the browser refreshes when the code changes on disk. 

But the **magic** is that the Streamlit cache "understands" which parts of your code has changed. So if your function has changed you will rerun it. Otherwise you will use the cached result.

When you try this it appears as magic because it works great and your development workflow becomes super fast. Its a visual oriented work flow where you inspect the changes in the Browser (not a TDD workflow).

I believe the Streamlit caching is actually something that is essential for any other data app framework in Python like Bokeh, Panel or Dash.

So my request is for DiskCache to support this as I can see its a great cache framework to use.

I believe this can be implemented by adding a hash key generated from the function code.

It would be nice to turn the functionality on during development and off during production.

Disclaimer: I run https://awesome-streamlit.org. Check it out :-)

**Comment by grantjenks** [comment]
Pull request welcome...
