### ISSUE TITLE
Fanout Cache iteration

### ISSUE THREAD

**Issue by MarkBaggett** [grantjenks/python-diskcache#169]
Hello Grant,
This is an **amazing** project.  Thank you. 

More of an FYI than an issue.  I noticed on the Fanout Cache that I can iterate over the cache object but iterkeys() returns nothing.  It isn't a problem for me but not what I expected based on behavior of Cache.  Here are steps to reproduce my result.

Create a cache and a few entries.

```
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from diskcache import FanoutCache
>>> c = FanoutCache("/tmp/example")
>>> c.set("Hello","World")
True
>>> c.set("Goodbye","World")
True
>>> c.get("Goodbye")
'World'
```

Enumerate with iterkeys() produces nothing.

```
>>> for x in c.iterkeys():
...    print(c.get(x))
... 
>>>
```

Enumerate with cache object works fine.

```
>>> for x in c:
...    print(c.get(x))
... 
World
World
>>> 
```

Here is my version info:

```
$ pip show diskcache
Name: diskcache
Version: 5.0.3
Summary: Disk Cache -- Disk and file backed persistent cache.
Home-page: http://www.grantjenks.com/docs/diskcache/
Author: Grant Jenks
Author-email: contact@grantjenks.com
License: Apache 2.0
Location: /home/me/venvs/test_diskcache/lib/python3.6/site-packages
Requires: 
```

**Comment by grantjenks** [comment]
Oops, that's kinda a footgun. FanoutCache doesn't support iterkeys(). The newest version, 5.1.0 will turn access into an error.

If you want a dictionary-like interface, consider using a diskcache.Index data type.
