### ISSUE TITLE
Popping items from cache requires some hacking, am I doing it wrong ?  

### ISSUE THREAD

**Issue by ebturo** [grantjenks/python-diskcache#171]
I'm using `cache.memoize` to cache function calls.  It works great, except in certain cases where I'm passing `kwargs` and need to pop specific items from the cache.  Here is an example:

```bash
In [1]: list(cache)[-1]
Out[1]:
('my_package.my_module.my_func',
 ENOVAL,
 'config',
 my_packakge.my_module.MyClass,
 'constraints',
 None)

In [2]: cache.pop(list(cache)[-1])

In [3]: list(cache)[-1]
Out[3]:
('my_package.my_module.my_func',
 ENOVAL,
 'config',
 my_packakge.my_module.MyClass,
 'constraints',
 None)
```

Which is not the expected behavior.  Here is my hackish solution to this issue:

```python
def clear_cache(cache, slice):
    """Use it like this:

        > utils.clear_cache(cache, np.s_[<start_index>:<end_index>])
    """
    from diskcache import ENOVAL
    for key in list(cache)[slice]:
        key = tuple(ENOVAL if str(v) == 'ENOVAL' else v for v in key)
        cache.pop(key)
```

Maybe should incorporate this logic into the `cache.pop()` method so I don't need to do it every time ?

**Comment by grantjenks** [comment]
Memoized functions have a `func.__cache_key__` function that you can use to create cache keys. Here's a demo:

```
In [17]: !rm -r /tmp/diskcache                                                  

In [18]: import diskcache                                                       

In [19]: cache = diskcache.Cache('/tmp/diskcache')                              

In [20]: @cache.memoize() 
    ...: def test(*args, **kwargs): 
    ...:     print('Running test with', args, kwargs) 
    ...:                                                                        

In [21]: test(1, 2, 3, x=4, y=5, z=6)                                           
Running test with (1, 2, 3) {'x': 4, 'y': 5, 'z': 6}

In [22]: test(1, 2, 3, x=4, y=5, z=6)                                           

In [23]: key = test.__cache_key__(1, 2, 3, x=4, y=5, z=6)                       

In [24]: del cache[key]                                                         

In [25]: test(1, 2, 3, x=4, y=5, z=6)                                           
Running test with (1, 2, 3) {'x': 4, 'y': 5, 'z': 6}

In [26]: test(1, 2, 3, x=4, y=5, z=6)                                           
```

**Comment by ebturo** [comment]
That's handy.  Thanks for sharing.  It doesn't completely address my use case though.  

Sometimes it's not so easy to reconstruct the arguments that I passed to a function call.  In your example it's not hard because each of your arguments has a primitive type.  But in my example I'm passing and instance of `MyClass`.  And `MyClass` isn't easy to reconstruct on the fly.  Luckily, I don't have to recreate `MyClass`.  Instead, I can call `list(cache)`, find the index `i` of the function call that I want to remove from the cache, and then call `cache.pop(list(cache)[i])`.  Except there is a problem because this only works with function calls that don't use `kwargs`.

**Comment by ebturo** [comment]
This brings up another related issue.  Suppose I am developing some new functionality where I am caching a function call that passes an instance of `MyClassAlphaRelease`.  At some point I realize that `MyClassAlphaRelease` needs new attribute.  Oops !  Better remember to remove the associated function calls from the cache before you make those changes, because there is no way to remove them later.  If I forget, my only recourse is to clear the entire cache and start over.  **Basically I want an option to pop or delete an object from the cache by index, not by key**.

Some context on my use case might be helpful here.  I use `diskcache` to develop ETLs.  Consider the following workflow: 1) query data from database to create a dataset; 2) find all unique values from one of the columns from my dataset; 3) generate an html file that lists the unique values, each in a unique color.  It seems logical to break this work into three methods, `load`, `extract`, and `display`, so I do that.  Each method is resource intensive, so I'm going to use diskcache to cache each stage of this workflow (even as I'm developing).  What an amazing time saver !

Now suppose I've nailed down `load` and it works exactly the way I want.  I'm still working on `extract` and `display`.  At first my call to `display` takes an instance of `Blacklist` as an argument, which is just a list of extracted values I'd like to ignore in my call to display.  Everything is great until I realize that I'd actually like to display blacklisted items in a color that can be configured by the user.  I'll implement this by adding a new `color` attribute to `Blacklist`.  Great, except, oh gosh I forgot to clean up my cache before updating my `Blacklist` class.  My only option is to clear the entire cache and re-run `load` (darn, that query takes over an hour to run!).

**Comment by grantjenks** [comment]
I think using the index of the key is a bit odd. What happens if you later need to insert a new stage between two others?

There's a primary key index inside the SQLite database but I don't want to expose it in the API. Sounds like your use case exceeds what memoize() was made for.

Maybe you should use the `tag` feature of the `memoize` decorator. That would let you mark all calls to a particular function that you could later evict in bulk. You could memoize a bunch of functions with `tag='stage-load'` and then later evict all keys with that tag.

Last option is to consider the `push()`, `pull()`, and `peek()` method calls on `Cache`. Those kind of implement the indexing that you want but were designed for implementing a "deque" data type.

**Comment by ebturo** [comment]
> I think using the index of the key is a bit odd. What happens if you later need to insert a new stage between two others?

Ah but the way I use `diskcache` this isn't an issue.  I use it in two ways: 1) interactively during development, and in this mode I look up the key before deleting; 2) for production releases to capture a snapshot of the ETL at various stages, and in this mode I rebuild the cache end-to-end for each release.

> Sounds like your use case exceeds what memoize() was made for.

Who cares what it's made for, I'm your user, and this pattern is damn useful.  It's like PySpark but lighter and and no JVM.

> Maybe you should use the tag feature of the memoize decorator. 

This won't work I need to remove elements based on the signature of my call.

> Last option is to consider the push(), pull(), and peek() method calls on Cache.

These don't seem to work with the `memoize` decorator: 

```bash
In [1]: list(cache)
Out[1]: [('load.my_dataset',)]

In [2]: cache.peek()
Out[2]: (None, None)
```
