### ISSUE TITLE
Support opening cache in read-only mode without locking?

### ISSUE THREAD

**Issue by LewisGaul** [grantjenks/python-diskcache#172]
Hey, I've just been trying out the package and it seems great.

I have the following situation I thought diskcache might be useful for: cache data somewhere on disk to be read from multiple short-lived processes, updated periodically, and with the data being locked only when it's being updated.

The problem I've found is that trying to open a cache in multiple processes seems to block on a SQL lock. What I want is for the data to be locked only when being written to, and not by connections that will be read-only. I wonder if there'd be a possible solution with a `read_only=True` option to `diskcache.Cache`, or if it's not feasible due to the current design?

Perhaps you know of a more suitable alternative? :)

```
$python -c "import diskcache; diskcache.Cache('__tmpdir').get('foo')"
^CTraceback (most recent call last):
  File "/mnt/c/Users/legaul/clue/venv36/lib/python3.6/site-packages/diskcache/core.py", line 2434, in reset
    (old_value,), = sql('PRAGMA %s' % (pragma)).fetchall()
sqlite3.OperationalError: locking protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/c/Users/legaul/clue/venv36/lib/python3.6/site-packages/diskcache/core.py", line 479, in __init__
    self.reset(key, value, update=False)
  File "/mnt/c/Users/legaul/clue/venv36/lib/python3.6/site-packages/diskcache/core.py", line 2434, in reset
    (old_value,), = sql('PRAGMA %s' % (pragma)).fetchall()
KeyboardInterrupt

**Comment by grantjenks** [comment]
What's your platform? Judging by the path: /mnt/c/Users/... are you on WSL? A quick Google search shows that SQLite and WSL have some history of issues: https://github.com/microsoft/WSL/issues/2395

Beware the caveats of DiskCache/SQLite: http://www.grantjenks.com/docs/diskcache/tutorial.html#caveats There are issues with NFS as well... not sure if that's in play here.

Otherwise it works fine for me on Mac and in CI on Linux and Windows:

```
$ ipython -c "import diskcache; diskcache.Cache('__tmpdir').get('foo')"
```

**Comment by grantjenks** [comment]
One other note: a "read_only" mode shouldn't be necessary. DiskCache is both multi-thread and multi-process safe.

**Comment by SoundsSerious** [comment]
@grantjenks Hi i can also report that this is a problem, but only on WSL where file locks aren't respected. I realize this is an edge case, but the multi-threading / multi-procress aspect does not work as intended here. Using disk cache without locks would work for me.

**Comment by grantjenks** [comment]
For reference, there was an attempt to create a  “read only” mode for Disk Cache. The work is still present in the query-only-support branch at https://github.com/grantjenks/python-diskcache/tree/query-only-support

@SoundsSerious Disk Cache acquires locks during initialization. But afterwards, the default settings for get() will not require locks for reading.

**Comment by LewisGaul** [comment]
Sorry, I missed your replies back in November. Yes this was on WSL - if it's only an issue there then the issue being closed seems appropriate! Maybe I should have less trust in WSL behaving properly and test things out elsewhere before reporting...

**Comment by SoundsSerious** [comment]
Good news! It turns out WSL2 has full support for file locks so this really isn't affecting me any more.

@LewisGaul maybe you can try upgrading your WSL and seeing if that fixes your issue?

**Comment by LewisGaul** [comment]
@SoundsSerious thanks for letting me know. I have tried upgrading to WSL2 and found multiple problems with it compared to WSL1, but I'm hoping those issues will go away one day. Good to have a clear picture of where the issues are seen anyway.

**Comment by audetto** [comment]
> For reference, there was an attempt to create a “read only” mode for Disk Cache. The work is still present in the query-only-support branch at https://github.com/grantjenks/python-diskcache/tree/query-only-support
> 
> @SoundsSerious Disk Cache acquires locks during initialization. But afterwards, the default settings for get() will not require locks for reading.

I still think that it would have been a great addition to DiskCache, but unfortunately there was no interest in the feature.
Hope it will change in the future.
