### ISSUE TITLE
diskcache created with python2 can't be read from python3

### ISSUE THREAD

**Issue by HassankSalim** [grantjenks/python-diskcache#173]
diskcache==4.1.0

dc_path = '/tmp/diskcache/data'

# python2 
dc = Cache(dc_path)
dc['shared'] = {'key': 'val'}

# python 3
dc = Cache(dc_path)
dc.get('shared')  # returns None 

is this a bug or was it done to avoid some serialization problems.

**Comment by grantjenks** [comment]
You’ll need to set the disk_pickle_protocol explicitly. Your Python 2 and 3 code are using different versions (the default is to use “latest”). I think Python 2 uses version 2 and Python 3 will use version 4 or something by default. The serialized version of the key in Python 3 is different than in Python 2 when different pickle protocols are used so the lookup fails.

I would be cautious about using a serialization format like Pickle across Python versions. It wasn’t really designed for that. Try using a more standardized format like JSON with JSONDisk from the docs.
