### ISSUE TITLE
possible unexpected overwrite

### ISSUE THREAD

**Issue by Cologler** [grantjenks/python-diskcache#175]
https://github.com/grantjenks/python-diskcache/blob/40ce0dedb90ccefacaea41ac11c19ddd491d5a6d/diskcache/core.py#L210

Is possible to use 'xb' open mode to avoid unexpected overwrite?

**Comment by grantjenks** [comment]
It might be possible but it seems extremely unlikely. The design supports overwriting values if a overridden Disk.filename() chooses to return the same file name for the same (key, value) item.

The default implementation uses 16 random bytes which is the same as a guid/uuid. See Collisions on https://en.m.wikipedia.org/wiki/Universally_unique_identifier for details as to likelihood.

It might be worth a disk parameter to support customization. I’m curious if the test suite passes with it changed.

Is this a concern from reading the code or do you suspect a value was overwritten?

**Comment by Cologler** [comment]
Just a concern from reading the code. UUID is safe because when inserting an existing UUID into a database, the database will raise an exception by default.

The default behavior of `Disk` should never overwrite a file. If a subclass of `Disk` is expected to overwrite a file, should that be implemented on the subclass?

Another issue is to allow overwrite a file will break the major feature `Thread-safe and process-safe`.

The other idea is replace `open(full_path, 'wb')` to `self.open_file(full_path)`  so the subclass can easier override the `Disk` class, how about this?

**Comment by Cologler** [comment]
I just realize there is another bug if the `Disk.filename()` will return the same file name for the same `key`: 

https://github.com/grantjenks/python-diskcache/blob/40ce0dedb90ccefacaea41ac11c19ddd491d5a6d/diskcache/core.py#L772-L805

the `cleanup` function will remove the file after `store` it.

**Comment by grantjenks** [comment]
Ok, I’m mostly convinced. Try changing the mode to “xb” and running the test suite. If that passes then it’s probably a fine change.

**Comment by Cologler** [comment]
All tests passed, but it still may raise `FileExistsError` someday when the randomly generated filename is duplicate. I think this is acceptable just like disk full error.

**Comment by Jerry-Ma** [comment]
I am subclassing the `Index` class as a convenient file storage backend and in my custom implementation of the `filename` method , I return the same path for the same key on purpose. Would it be possible to allow subclass to modify the default behavior of `open` inside the `store` function? One approach is to provide a `open_file()` method as what Cologler was suggested. What do you think?

Edit: apparently I didn't check the latest code. I see there is already the "_write" method. Sorry for the noise.
