### ISSUE TITLE
Unable to open database file with a process pool

### ISSUE THREAD

**Issue by cipri-tom** [grantjenks/python-diskcache#179]
Hi,

Thanks for diskcache and especially for all its awesome utilities and recipes ! 

### Context 
I am using it to cache data from an API, which should also be throttled. So I'm using `memoize()` and `throttle()` around my request function. All this runs in a multiprocessing environment, which brought me to diskcache in the first place.

Am I right to expect diskcache to work with multiprocessing out of the box (relying on DB transactions), or should I use Locks, especially for that multi-process throttling ?

### Problem

Running some tests locally (macOS), all seems fine, I accomplish what I need -- unseen values are queried to the API, with the correct rate, while seen values are returned from cache. 

However, running it with more data in "pre-prod" (linux, Ubuntu), I encounter a weird `sqlite3.OperationalError: unable to open database file`. The code works well for a while, but then stops with this error, with the following stack trace:

<details><summary>Stack trace</summary>

```
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/concurrent/futures/process.py", line 367, in _queue_management_worker
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/multiprocessing/connection.py", line 251, in recv
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/site-packages/diskcache/core.py", line 2370, in __setstate__
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/site-packages/diskcache/core.py", line 457, in __init__
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/site-packages/diskcache/core.py", line 649, in _sql_retry
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/site-packages/diskcache/core.py", line 644, in _sql
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/site-packages/diskcache/core.py", line 621, in _con
sqlite3.OperationalError: unable to open database file
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "batch_evaluation.py", line 208, in <module>
    run_multiple_ds(paths_df, ds_names, args.output)
  File "batch_evaluation.py", line 185, in run_multiple_ds
    write_outputs_to_disk(results, paths_df, ds_names, output_dir)
  File "batch_evaluation.py", line 121, in write_outputs_to_disk
    for out_path, result in results:
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/ciprian/miniconda3/envs/my-env/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
</details>

I am not able to catch this error in my code to further inspect it, because it is happening when the `cache` object is unpickled after being passed from one process to another.

Some users on StackOverflow [suggest](https://stackoverflow.com/a/57729827/786559) this may arise when the sqlite3 db becomes corrupted.

I believe this may happen due to the use of `throttle()`:
 - it uses `cache.transact()` https://github.com/grantjenks/python-diskcache/blob/c4ba1f78bb8494bcf6aba9d7d1c3aa49a1093508/diskcache/recipes.py#L254
 - in turn, this uses `threading.get_ident()` to manage the transaction: https://github.com/grantjenks/python-diskcache/blob/c4ba1f78bb8494bcf6aba9d7d1c3aa49a1093508/diskcache/core.py#L712
 - a small test shows that the `get_ident()` may return the same identity while the process is different:
 ```python
from concurrent.futures import ProcessPoolExecutor
import threading
import os

def f(i):
    print(threading.get_ident(), os.getpid(), flush=True)


with ProcessPoolExecutor(max_workers=3) as pool:
    pool.map(f, range(10))
```
Outputs
```
139819087464256 6165
139819087464256 6165
139819087464256 6166
139819087464256 6167
139819087464256 6165
139819087464256 6165
139819087464256 6166
139819087464256 6167
139819087464256 6165
139819087464256 6166
```

So I believe this may result in a database corruption, as process P2 may `COMMIT` under the identity of process `P1`.

What do you think ? Could this be the cause, or should I look deeper in my code ?

Many thanks  for the awesome library!

**Comment by grantjenks** [comment]
Duplicate thread ids shouldn't be a problem. They are expected to be unique only on a per-process basis. The thread id logic in diskcache is implemented to support nested transactions (known as reentrancy) within the same thread.

Could you post a reduced repro with the use of ProcessPool and throttle? The logic of the worker can just be time.sleep. It's otherwise hard to guess what is happening.

A problem like this sounds vaguely familiar and I think the solution may have been to pass the cache reference as an argument to the target function. I'm forgetting the details but that helped one person.

Another idea is that the SQLite on the Linux machine is older than the SQLite on your Mac. It may not be respecting all the pragmas used by the library. Could you "git clone" the repro and run "python setup.py test"

**Comment by cipri-tom** [comment]
Hi @grantjenks 

Thanks for the quick reply ! 
The tests all pass, so SQLite seems fine. For the reference, it is `sqlite --version 3.34.0 2020-12-01 16:14:00`.

I have discovered a couple of errors in my code. While they are not related to threading, they do cause uncaught exceptions on the worker threads. It seems that these are not reported on the main thread until the result from that broken process is retrieved. I am thinking that this might be a source of inconsistency in the database.

I will fix them first then re-try my experiment and, if error persists, try to build a reproducible example.

Thank you for your support ! I'll report back soon

**Comment by cipri-tom** [comment]
Hi @grantjenks ,

I have fixed the previously mentioned errors, so that the processes no longer break.

However, I stil have the error. I have written [here](https://gist.github.com/cipri-tom/2350395280537544ed9a2991747ea412) a minimal example that reproduces the problem. I have copied the implementation for `throttle` and `memoize` in classes, which allow it to be pickle-able and sent between processes.

The error is usually thrown in `reset()`:
```
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
  File "/home/ciprian/miniconda3/envs/pdf-fraud-indep/lib/python3.7/concurrent/futures/process.py", line 367, in _queue_management_worker
  File "/home/ciprian/miniconda3/envs/pdf-fraud-indep/lib/python3.7/multiprocessing/connection.py", line 251, in recv
  File "/home/ciprian/miniconda3/envs/pdf-fraud-indep/lib/python3.7/site-packages/diskcache/core.py", line 2371, in __setstate__
  File "/home/ciprian/miniconda3/envs/pdf-fraud-indep/lib/python3.7/site-packages/diskcache/core.py", line 479, in __init__
  File "/home/ciprian/miniconda3/envs/pdf-fraud-indep/lib/python3.7/site-packages/diskcache/core.py", line 2436, in reset
sqlite3.OperationalError: unable to open database file
'''
```
I had a hard time to reproduce it until I have instrumented the `reset()` method to print when it is called: `print(f'Resetting from {current_process().name}')` as first line.

This way, I noticed four patterns:
1. if I don't return the `api` object from the process, i.e. only `api.get_n(n)` here: 
https://gist.github.com/cipri-tom/2350395280537544ed9a2991747ea412#file-test_throttled-py-L12-L14

then it prints about resetting from each pool process:
```
$ python test_throttle.py 2 |  uniq -c
     33 Resetting from ForkProcess-1
     33 Resetting from ForkProcess-2
```

2. However, in the actual code, I saw a lot of `Resetting from MainProcess`, so I figured there must be an `api` object travelling back to the main thread, where it is recreated. Hence the tuple return in line 14. This did not change the output
3. I actually used the `api` object on the main process, which finally results in the error (activate by passing a 2nd argument to the test script): 
```
$ python test_throttle.py 2 1 |  uniq -c`
... 
sqlite3.OperationalError: unable to open database file
...
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running
  16161 Resetting from MainProcess
```

4. re-running case `2.` after case `3.` results in:
```
$ python test_throttle.py 2 |  uniq -c
  16161 Resetting from MainProcess
```
so only `MainProcess`, again, as in case `3.`

In my reall code, I see both ForkProcesses and MainThread activating the `reset()` path.

Thank you for having a look into this! !
I hope this can shed some light onto what is going on. Maybe I'm doing a big No-No when overriding `throttle` ? 

Many thanks !
Ciprian

**Comment by grantjenks** [comment]
How long do the tests take you to run? It seems like your cache must be warmed with results.

**Comment by grantjenks** [comment]
Also, what platform are you running on? Windows, Mac, Linux? And your Python version is CPython 3.7?

**Comment by grantjenks** [comment]
Sadly, I am not able to reproduce the problem locally. It has run for a long time so I'm not sure I'm running it correctly. I've tried some variations with warming the cache but it works the same.

I'm concerned by this comment in the code: "to make them pickle-able". Why do the functions need to be pickle-able? Pickling the cache is problematic because deserializing it means re-initializing the cache object. From the docs at http://www.grantjenks.com/docs/diskcache/tutorial.html#cache :
```
opening Cache objects is relatively slow, and since all operations are atomic, may be safely left open.
```
As much as possible, the best practice is to open the cache once, as a global variable, and use that in all code references. Passing a cache between processes might require pickling and cause re-initialization.

It's suspicious that the exception occurs in reset() because the reset() method is called during cache initialization to set a bunch of pragmas. I've seen in other rare cases that setting the pragmas can cause race conditions that yield exceptions (like the OperationalError observed). Can you try this script:

```python
import diskcache as dc

from concurrent.futures import ProcessPoolExecutor


def init(n):
    cache = dc.Cache('/tmp/stress')
    return n


def main():
    with ProcessPoolExecutor(64) as pool:
        results = list(pool.map(init, range(10_000)))
    print('Results', len(results))


if __name__ == '__main__':
    main()
```

And also this one:

```
import diskcache as dc

from concurrent.futures import ProcessPoolExecutor


cache = dc.Cache('/tmp/diskcache-read')
cache['key'] = 42


def read(n):
    return cache['key']


def main():
    with ProcessPoolExecutor(64) as pool:
        print('Creating generator ...')
        generator = pool.map(read, range(100_000))
        print('Gather results ...')
        results = list(generator)
        print('Shutting down pool ...')
    print('Summing results ...')
    print('Results', sum(results))


if __name__ == '__main__':
    main()
```

Each of those work for me without issue.

One more suggestion: use multiprocessing.Pool instead of concurrent.futures.ProcessPoolExecutor. The tracebacks from multiprocessing are easier to read and understand.

**Comment by cipri-tom** [comment]
Hi @grantjenks !

Thank you so much for looking into this with remarkable attention ! 

As you have correctly noticed on the gist, the throttling was very aggresive: 1 call every 2 seconds. For 1800 expected objects, this takes at least 1 hour to run. I'm sorry I forgot about this and made you wait. I have now updated to 20 calls / 2s and I still have my error after ~1m50s, even with a new cache. 

The magic incantation is: `time python test_throttle.py 2 1` . The `1` at the end is important, as you have realised. Without it, results are not accessed on the main thread, and no error is raised.

The variables in the test script are:
 - `nums` - how many different items we query
 - `tests` - how many times we query one of these `nums` items
 - `ws` - probabilities of querying the `nums` <--  a Normal distribution : some items are queried a lot, some are only queried once

---

> Passing a cache between processes might require pickling and cause re-initialization.

This is exactly what is happening! 
Each function call serializes the cache object at least once -- once for sending and once for receiving. I solved the sending part by creating `cache` once per when process, during the initialization.
And this is also why I needed the functions to be pickleable -- so they work with process pool. 

I see that the tests you propose attempt to stress this use case - many initialisations and many reads. They both pass on my machine too (Linux, Ubuntu 18.04, CPython 3.7.9).

--- 

1. Can you please re-try the gist ? Since I reduced the throttling it should go much faster. Is it possible that you also try under Linux ? I think process forking is different under Windows and Mac.
2. Is it possible that [crazycoder65 on StackOverflow](https://stackoverflow.com/a/57729827/786559) is right, or that makes no sense since all operations are atomic ? (even with `cache.transact()` in `throttle`)
3. I believe this may be a race condition of the pragmas caused by the myriad of re-initialisations. Judging from the code of `diskcache` and your other software, I see you are a very skilled architect. Do you have any suggestion for how I can avoid pickling the cache object (thus its re-initialization) ? of course, one way would be to take it out of the API object, but then the user of my library would have to create it before making their process pool.

Thanks for the suggestion of `multiprocessing` instead of `concurrent.futures`. I opted for the latter as I saw `mp` can deadlock when one of the processes quits unexpectedly (or has some very bad exception) -- it has happened to me. But I will try and see if it improves.

**Comment by grantjenks** [comment]
1. I still cannot repro with the gist :( My hardware maybe too small for the needed concurrency. Outside of work, I'm using a macbook air.
2. I doubt the cache is corrupted. The issue is with the pragmas during initialization.
3. I'm not sure the best way to do it but you'd need to make the cache reference a global. Maybe provide a default cache as a global and support customization of the global reference using the "global" statement in Python.

Re: `concurrent.futures.ProcessPoolExecutor` vs. `multiprocessing.Pool`. The latter is older and tends to be a bit more robust in my experience. Great that it works.

**Comment by cipri-tom** [comment]
Sorry I have no longer provided an update on this, that project was taken over by a different team.

I would like to confirm your solution / intuition:
_The pragmas during initialization are the issue._

I identified the issue by inspecting deeply the diffrences between `concurrent.futures.ProcessPoolExecutor` and `multiprocessing.Pool`, and adding some `print()`s in `diskcache`'s code. It's all due to the default of the `chunksize` parameter which I had not specified:
 - `ProcessPoolExecutor` uses `chunksize=1`
 - `mp.Pool` calculates chunksize so that each worker gets ~4 chunks

Therefore, as the `cache` object was reconstructed each time it was passed between processes, there were a lot more initializations with `ProcessPoolExecutor` than with `mp.Pool`.

Changing to use a global `cache` variable made the code simpler and eliminated the problem. I shouldn't have avoided the global variable so strongly.

Thank you !

**Comment by grantjenks** [comment]
Thanks for sharing.
