### ISSUE TITLE
Configuring large diskcache with 500 million entries

### ISSUE THREAD

**Issue by srinivasjdi** [grantjenks/python-diskcache#183]
Hi @grantjenks , Thanks for this library. Having fun playing with this ! This is not exactly an issue. But I need some help configuring the disk-cache. I want to create a really large cache that can hold 400-500 million entries (The data size is approx 50GB). The insertion is done using multiprocessing. I have a Fanout cache with 100 shards. I have two questions : 

1. What are the best config settings for tuning such a large cache ? Are there any failure modes that you have seen in such scenarios ?

2. Even though I create 100 shards, only the first 8 seem to be getting used. (I checked by checking disk usage of the cache files in the 100 folders). Is there any setting that I'm missing or is this expected behaviour ?

Here is sample code for inserting 1 million entries.

```
from diskcache import Cache
from diskcache import FanoutCache
import os
import time
from itertools import repeat

cache_location = "/instnc_store/disk_fanout_cache_directory"

num_processes = 60

global cache 
cache = FanoutCache(cache_location, shards=100, time_out=10, size_limit=int(100e9), cull_limit=0)

def insert_single_file():
	print("started single process fanout cache benchmark")
	global cache
	start_time = time.time()
	batch_start_time = time.time()
	with FanoutCache(cache.directory) as reference:
		with open(file_name) as f:
		    for line in f:
		        rs = ''.join(random.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for _ in range(6))
		        nl = line + rs
		        reference.set(nl,1)
		        itr += 1
		        if itr%10000 == 0:
		            print("Time taken for batch of 10000: " + str(time.time()-batch_start_time))
		            batch_start_time = time.time()
		        if itr == 100000:
		        	return

def insert_files_into_cache():
	pool = mp.Pool(processes=num_processes)
	try:
		pool.starmap(insert_single_file_into_cache)
	except Exception as e:
		print("Exception in pool: %s", e)
	finally:
		pool.close()
```

Thanks a lot.

**Comment by grantjenks** [comment]
Inside `insert_single_file` the statement `with FanoutCache(cache.directory) as reference:` is causing the issue. FanoutCache "remembers" the `sqlite_` and `disk_` settings that it is initialized with but it does not "remember" the `shards`, `timeout`, or `disk` arguments. Those arguments should generally be consistent across all initializations of the FanoutCache.

Add `shards=100` to the `with` statement and it'll use all 100 shards.

**Comment by grantjenks** [comment]
Also note that the `time_out=10` has a typo. It should be `timeout=10` for 10 seconds.

**Comment by grantjenks** [comment]
Also note that the FanoutCache can remain as a global reference. There's no need to re-initialize it inside the `insert_single_file` function. It will work across processes.

**Comment by grantjenks** [comment]
Here's a simplified version of the code:
```
import random
import time
import multiprocessing as mp

from diskcache import FanoutCache

cache_location = '/tmp/issue-183'

cache = FanoutCache(
    cache_location,
    shards=100,
    timeout=10,
    size_limit=int(100e9),
    cull_limit=0,
)


def insert_keys(count):
    for _ in range(count):
        key = random.randrange(500_000_000)
        cache.set(key, key)


if __name__ == '__main__':
    start = time.time()
    pool = mp.Pool(8)
    pool.map(insert_keys, [1_000] * 8)
    pool.close()
    stop = time.time()
    print('Duration:', stop - start, 'seconds.')
```
And then running it:
```
$ python -i tests/issue_183.py 
Duration: 1.7480089664459229 seconds.
>>> len(cache)
8000
>>> [len(shard) for shard in cache._shards]
[77, 73, 84, 80, 69, 78, 81, 82, 72, 91, 73, 85, 81, 75, 77, 80, 79, 78, 74, 86, 79, 77, 69, 77, 86, 71, 74, 79, 75, 75, 90, 76, 78, 82, 73, 90, 76, 81, 68, 81, 83, 65, 71, 93, 84, 73, 92, 86, 97, 79, 82, 82, 78, 84, 71, 89, 77, 75, 96, 95, 76, 79, 100, 85, 74, 89, 73, 78, 79, 71, 71, 90, 78, 89, 64, 72, 86, 79, 78, 80, 73, 78, 63, 91, 75, 67, 66, 87, 76, 86, 102, 75, 75, 92, 89, 91, 80, 87, 85, 87]
```
Storing 500 million keys is a lot but shouldn't be an issue.

Note that "shards" are only meant to reduce concurrency issues. If you don't have 100 processors then 100 shards is probably excessive.

**Comment by grantjenks** [comment]
One last thing, for bulk insert of items, using a transaction for chunks of keys (like 1,000 or more) using “cache.transact()” will be faster than individual inserts. The optimal chunk size will vary based on the item size and hardware.

**Comment by srinivasjdi** [comment]
I'll continue with the benchmarking and record my results here. Actually, I'm testing this out on m5d.24xlarge machine (with 96 cores) and 100+ processes. Thanks a lot !
