### ISSUE TITLE
Listen to cache events

### ISSUE THREAD

**Issue by sdementen** [grantjenks/python-diskcache#185]
Is it possible to listen to cache events (addw expire,...) from the processes/threads that connects to a same cache?
To see if disk cache could be used for IPC and sync between processes/threads.

**Comment by grantjenks** [comment]
Needs more details.

**Comment by sdementen** [comment]
Multiple processes or threads connects to the same cache. If one process updates the cache, how can ane of the other processes be notified? Could they listen to some key/tag and receive events like "added/updated/deleted/expired/..."

**Comment by grantjenks** [comment]
No, I’m not aware of a feature like that built into SQLite. I typically use polling with some kind of queue.

**Comment by sdementen** [comment]
Maybe with something like what is done here https://stackoverflow.com/questions/16872700/sqlite-data-change-notification-callbacks-in-python-or-bash-or-cli

**Comment by sdementen** [comment]
But I just read https://stackoverflow.com/questions/677028/how-do-i-notify-a-process-of-an-sqlite-database-change-done-in-a-different-proce#comment84679512_22390871

**Comment by grantjenks** [comment]
As I said, I’m not aware of a feature like that built into SQLite. Polling with 10ms delays is likely not so bad ... I've made it work ;)
