### ISSUE TITLE
Async Implementation

### ISSUE THREAD

**Issue by thedrow** [grantjenks/python-diskcache#186]
Currently, the cache operations are blocking.
If we can use threads for the operations, we can use AnyIO's blocking portal for compatibility with any event loop.

It should be pretty easy to implement but I'd like your feedback first.

**Comment by grantjenks** [comment]
The tutorial page at the bottom has an example of using async: http://www.grantjenks.com/docs/diskcache/tutorial.html#caveats

I’m not familiar with AnyIO. Link?

**Comment by jab** [comment]
See https://anyio.readthedocs.io. The main benefit is to be able to support both `asyncio` (since it's built in) and [Trio](https://trio.readthedocs.io), which many users prefer because it enables [structured concurrency](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/) (a huge benefit) at the same time. Definitely check out that blog post and the [PyCon talk](https://www.youtube.com/watch?v=oLkfnc_UMcE) if you haven't already. (And if you've never tried writing an implementation of Happy Eyeballs that correctly handles all the edge cases, trying with asyncio and then with Trio really proves the point.)

**Comment by grantjenks** [comment]
The AnyIO api looks pretty similar to asyncio: https://anyio.readthedocs.io/en/stable/threads.html

What’s to be implemented?

**Comment by thedrow** [comment]
I think we need a class which wraps the current API and schedules the execution of the methods in worker threads which you can `await` until they are completed.

**Comment by grantjenks** [comment]
Maybe. I think it would look mostly like: (from the docs)
```
import asyncio

async def set_async(key, val):
    loop = asyncio.get_running_loop()
    future = loop.run_in_executor(None, cache.set, key, val)
    result = await future
    return result

asyncio.run(set_async('test-key', 'test-value'))
```
Repeated for all the methods. Given the number of methods, data types, and async libs, it seems like a significant amount of boilerplate code. It also doesn’t answer how the executor may need to be customized. Should the executor simply be the default? Or per Cache? Or itself customizable? And that might change the API in some places.

Perhaps there is a kind of utility metaclass that can do all the wrapping automatically. Is there a kind of AsyncMixin that can wrap all the methods with the thread pool executor pattern?

**Comment by thedrow** [comment]
We can write one if we want to.

**Comment by grantjenks** [comment]
See #193 . I'm skeptical the code belongs in python-diskcache. Looks pretty generic. Maybe it belongs in an asyncio utils library?

**Comment by thedrow** [comment]
I don't see why it shouldn't be.
Also, we need AnyIO for compatibility with trio as well.
If you are not interested, I can do it myself when I get to it.

**Comment by grantjenks** [comment]
I updated PR #193 but will add here for posterity. This is as far as I got:

```
class AsyncMeta(type):
    def __new__(cls, name, bases, attrs):
        base = attrs['__wrapped__']

        def __init__(self, loop=None, executor=None):
            if loop is None:
                loop = asyncio.get_event_loop()
            run = functools.partial(loop.run_in_executor, executor)
            self.__dict__['_async_meta_run'] = run
            self.__dict__['_async_meta_thing'] = None

        assert '__init__' not in attrs
        attrs['__init__'] = __init__

        async def initialize(self, *args, **kwargs):
            """Initialize the thing attribute."""
            func = functools.partial(base, *args, **kwargs)
            thing = await self._async_meta_run(func)
            self.__dict__['_async_meta_thing'] = thing

        assert 'initialize' not in attrs
        attrs['initialize'] = initialize

        def __getattr__(self, name):
            return getattr(self._async_meta_thing, name)

        assert '__getattr__' not in attrs
        attrs['__getattr__'] = __getattr__

        def __setattr__(self, name, value):
            setattr(self._async_meta_thing, name, value)

        assert '__setattr__' not in attrs
        attrs['__setattr__'] = __setattr__

        def __delattr__(self, name):
            delattr(self._async_meta_thing, name)

        assert '__delattr__' not in attrs
        attrs['__delattr__'] = __delattr__

        # TODO: Add support for __aiter__, __anext__, __aenter__, and __aexit__

        def make_method(func):
            """Make an async wrapper method."""
            @functools.wraps(func)
            async def method(self, *args, **kwargs):
                """Async wrapper method."""
                # `AsyncThing` wraps `Thing` so pass `self._async_meta_thing` as the
                # first argument to be bound to `self` in `Thing` method calls.
                call = functools.partial(func, self._async_meta_thing, *args, **kwargs)
                return await self._async_meta_run(call)
            return method

        # Iterate the attributes of the cache and make methods for `AsyncCache`.

        for name in dir(base):
            if name.startswith('_'):
                # Only support the "public" methods.
                continue
            attr = getattr(base, name)
            if not isinstance(attr, types.FunctionType):
                continue
            # TODO: Add support for contextlib.contextmanager types.
            method = make_method(attr)
            attrs[name] = method

        bases = (object,)
        return super().__new__(cls, name, bases, attrs)


class AsyncCache(metaclass=AsyncMeta):
    __wrapped__ = Cache
```

This class is entirely generic and would work with any non-async class. I'm happy to see it included in a library like asyncio or anyio but I don't need it currently and so am ill-suited to maintain it.

Something more will require a consulting engagement.
