### ISSUE TITLE
collections.deque maxlen equivalent

### ISSUE THREAD

**Issue by wiryonolau** [grantjenks/python-diskcache#190]
Hi while Deque have same function as collections.deque but it missing the maxlen function.

Is there a solution to remove the most right when push from left and maxlen is reach, and vice versa using Deque.

Or I should use Cache instead and pass collections.deque ?

**Comment by grantjenks** [comment]
That's correct, diskcache.Deque does not implement the "maxlen" parameter.

It's possible to use Deque.transact() to keep the length of the Deque in check.

**Comment by grantjenks** [comment]
Released in v5.6.0
