### ISSUE TITLE
Example app using DiskCache with Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [grantjenks/python-diskcache#192]
Hi @grantjenks 

This is just for your info. I've now successfully been using DiskCache for a while. Just wanted to reach out with a THANKS.

You can find an example app here https://awesome-panel.org/caching-example

and video https://twitter.com/MarcSkovMadsen/status/1355838430521995265?s=20

Thanks again.

![image](https://user-images.githubusercontent.com/42288570/106383051-c633fb00-63c3-11eb-9f6b-802346021f47.png)

**Comment by grantjenks** [comment]
Nice video. Thanks for sharing.

Not sure how it’s implemented but often for data apps, the memoize() decorator is sufficient. One thing I’ve done is layer caches like so:
```
@some_redis_module.memoize()
@disk_cache.memoize()
@functools.lru_cache()
def expensive_func():
    ...
```
Now cache lookups hit memory first, then disk, and finally the network. If none of those have the key then it is recomputed by expensive function. You might add a note that cache layering is possible and it’s generally not a matter of using only one.

**Comment by MarcSkovMadsen** [comment]
Thx. Will do.
