### ISSUE TITLE
Memoize and class / instance methods

### ISSUE THREAD

**Issue by wlupton** [grantjenks/python-diskcache#194]
I was playing with memoize on an instance method and notice that the instance is part of the key calculation. Of course, this is correct, but there's stuff in the instance that is preventing the desired caching behaviour (I haven't looked into the details). So I'm thinking that I need to override the key calculation. However, the approach shown below is the only way that I can think of to achieve this. This works, but it seems rather complicated (here I'm ignoring the instance, but of course I could use some of its attributes).

I realize that I could refactor things so I'm memoizing some lower-level static function, but ideally I'd like not to have to change the existing class (apart from adding the decorator and maybe a custom key calculation function). Any thoughts? Probably I'm missing something obvious.

```
class Server:
    ...
    
    @cache.memoize(expire=3600)
    def search(self, entity_type, property_name, search_string):
        ...

    __original_cache_key__ = search.__cache_key__

    def __replacement_cache_key__(self, *args, **kwargs):
        print('__replacement_cache_key %r %r' % (args, kwargs))
        key = self.__original_cache_key__(*args, **kwargs)
        # omit self (requires undesirable knowledge of the key structure)
        return key[:1] + key[2:]

    search.__cache_key__ = __replacement_cache_key__
```

**Comment by grantjenks** [comment]
I think you can stack @staticmethod atop the memoize decorator and drop the self parameter.

**Comment by wlupton** [comment]
Thanks. This is an existing method and it can't be static (ideally I didn't want to change it). I realise that I could (and maybe should) do something like this, but mostly my question was about the intended use of `__cache_key__`.

```
    def search(self, entity_type, property_name, search_string):
        return self.search_((self.host, self.port), entity_type, property_name, search_string)

    @staticmethod
    @cache.memoize(expire=3600)
    def search(address, entity_type, property_name, search_string):
        ...
```

**Comment by grantjenks** [comment]
I hadn’t thought of re-assigning cache_key but I suppose that’s fine. Generally the cache key function is used to generate keys and evict previously cached results.

**Comment by wlupton** [comment]
OK. Thanks.

**Comment by wlupton** [comment]
FYI I came back to this and slightly improved my hack by creating this:

```
# decorator for replacing a function's memoize key function
# XXX this has undesirable knowledge of the key structure, and assumes that
#     the first argument is a CrowdServer (with a rest_url property)
def replace_memoize_key_func(func):
    original = func.__cache_key__

    def replacement(*args, **kwargs):
        key = original(*args, **kwargs)
        new_key = (key[0], key[1].rest_url) + key[2:]
        return new_key

    func.__cache_key__ = replacement
    return func
```

This can be used as a decorator as follows:

```
@replace_memoize_key_func
@cache.memoize(expire=3600)
def search(server: CrowdServer, ...):
    ...
```
