### ISSUE TITLE
Finding project links on GitHub requires scrolling

### ISSUE THREAD

**Issue by ssbarnea** [grantjenks/python-diskcache#201]
Current package metadata is missing some important links that those towards source code or issue tracker. That is why the presence on https://pypi.org/project/diskcache/ does not expose them on the left sidebar.

While I am not 100%, my impression is that adding the new fields would require replacing the deprecated use of setup.py with setup.cfg (this does not imply PEP-517.)

To give an example of a package using more metadata, look at https://pypi.org/project/mk/ and you will see more links including some exposing number of issues open and pull requires (this is done by pypi automatically). The magic properties that enable this are at https://github.com/pycontribs/mk/blob/main/setup.cfg#L13-L15

**Comment by ssbarnea** [comment]
Bottom of the page is not really easily discoverable, in fact it is likely to even require scrolling in order to spot it. What I am curious is if you have anything against using things like setuptools-scm, which can address these. If not, I would probably be able to propose a patch to upgrade packaging bits, and also address this aspect.

**Comment by grantjenks** [comment]
I’m open to switching to something better than setup.py for my projects but I haven’t found anything that beats the flexibility of a Python script. As a maintainer, it’s nice to use the same packaging tools for all my packages and I’ve found the newer tools don’t handle Cython/C modules so well.

Can setup.py really not support those links? Or could it live alongside setup.cfg? Maybe it’s easiest just to have both for a couple of extra links.

**Comment by AbhinavOmprakash** [comment]
@grantjenks hey, I just discovered this project on twitter but finding the repo was quite hard(I ended up googling it). I understand Changing the packaging tools you use is out of question. Maybe a link at the top of readme would be suitable?

**Comment by grantjenks** [comment]
Having read through the docs, I think it's just a matter of adding `project_urls` to setup() (https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls)

**Comment by AbhinavOmprakash** [comment]
I've made a pull request with the addition of `project_urls` to setup() have a look at it whenever you get time.
