### ISSUE TITLE
Using Index as a 'greater then memory' database/dict

### ISSUE THREAD

**Issue by ngodber** [grantjenks/python-diskcache#203]
Hi,

Firstly, thanks for the great work that has been done here. I've been searching unsuccessfully for a solution to interact with a greater than memory data set.  Index seems to offer that solution! I've a couple of questions that don't seem to have popped up in previous issues and documentation. 

For context, my dataset consists of dictionary of dataclasses with various int/float attributes and a few large numpy arrays. Unfortunately the numpy arrays are not of fixed length between classes so this data structure doesn't lend itself to HDF5 et al so I can't make use of typical larger-than-memory chunking type options. I also don't want to write each individual object out to disk individually as I think that would be inviting wanton IO bottlenecks. 

The first question, is it possible to set the reserved memory space to use in the cache before data are persisted to disk? If so, presumably data are persisted upon .close()? My eye here is on performance, as there will be some scenarios where data are not greater then memory I don't want to be triggering needless disk IO. 

Secondly I'm avoiding the use of pickle as its not a self describing format and I've been burnt many times with old pickles not reading either due to implementation changes on my end or in pickle itself. Before running into memory problems I've been using msgpack (with its msgpack-numpy support) to binary serialize each object. I assume it would be possible to implement this into Disk? I'd also be interested in your thoughts around this approach.

Thanks!

**Comment by grantjenks** [comment]
All items are immediately persisted to disk when written. If you want a memory-based write-back cache then you’ll have to implement it yourself. Every disk cache operation is atomic with the disk.

For msgpack support, yes, a custom Disk is the way to go. Look at the JSONDisk source for an example.

**Comment by ngodber** [comment]
Hey,

Ah ok. It was late last night so I think I got myself twisted around. Is there some form of in memory buffer with first in first out or does every reference imply a disk read?
So if a = Index ()
a[0] = {b:1}
* wait on disk write *
value = a[0]
* wait on disk read* 
value2 = a[0]
* wait on disk read*
If there is a memory buffer, is there a way to set its size?

**Comment by grantjenks** [comment]
Disk Cache doesn’t provide an in-memory buffer. You’d have to build that as a layer on top. I’ve thought about it before but there’s a fair amount of nuance and trade offs. In order to share data between threads and processes, the items have to land on disk.

If you want to do cached reads from memory, you could wrap Cache.get in functools.lru_cache pretty easily. I’m not sure of an easy way to delay writes.

**Comment by ngodber** [comment]
Ah right.  I don't see any real need to delay writes. Its more that those writes don't hold up the calling thread. It sounds like at the moment they do. Looking through the code it seems it would be quite a big job to implement a write queue. Alright, thanks a lot for your feedback.
