### ISSUE TITLE
Ability to configure database filename

### ISSUE THREAD

**Issue by ssbarnea** [grantjenks/python-diskcache#204]
I am writing a CLI tool that needs to cache information about different git repositories and I need to isolate executions happening from various repositories.

I am using standard `~/.cache/toolname` user folder for that and in order to avoid cross contamination of cache I want to use various caches for each repository (identified by its root folder location, which I can hash to few chars).

At this moment I am forced to use different folders for each instance because I cannot tell Cache to use different db filenames.

Could it be possible to allow db filename to be configurable?

I already considered using a single database for all the caches but I did not see any api that could be leveraged to isolate different instances. `Tag` looked interesting but `cache.get(name, tag)` does not work I was expecting (to retrieve a value from a particular tag or the defaut).

**Comment by grantjenks** [comment]
Look in core.py. You could move the DBNAME global var to an instance var.

Or you could just override it’s use in the “_con” method (DBNAME only has two uses and you could probably ignore the other).

Just changing the db file name may not be enough. What about values persisted in files? Seems like there could be collisions.

Also seems like you could create hierarchical keys pretty easily.at each use strings like “project/thing” and store all the things from different projects in one cache.

**Comment by ssbarnea** [comment]
I did consider using hierarchical keys but at this moment I fail to see any reason why I would want to store info from all these projects in a single database. I can only expect to affect load times with such an approach.

For the moment I will sue separated folders and decide later on which route to pick as my [mk](https://github.com/pycontribs/mk/) project is still experimental.

I will close the ticket as I do thing that private api use may be ok as alternative, at least for now. In the end, if I dislike using internals I could make a PR to expose them.

**Comment by kerrickstaley** [comment]
I would also like to be able to use a different database file name than `cache.db`. Ideally `diskcache.Cache.__init__` would have an argument to set this. Can we re-open this feature request?
