### ISSUE TITLE
Can I use uuid hex string or int (128-bit) for key?

### ISSUE THREAD

**Issue by jinserk** [grantjenks/python-diskcache#205]
Hi,
I wonder if I can use uuid as the key of Index. As far as I know, uuid has 128-bit string or int digest. If I use the uuid as the key of Index object, does it guarantee the uniqueness of the key?

If diskcache is using only 32-bit mask for the hash of the key, how can I replace the hash to the 128-bit one?
Thank you!

**Comment by grantjenks** [comment]
Sure. Disk Cache uses the full 128 bits if you use a string and now an integer. The max integer is 64-bit.

```
$ ptipython
Python 3.8.4 (v3.8.4:dfa645a65e, Jul 13 2020, 10:45:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import uuid

In [2]: import diskcache as dc

In [4]: cache = dc.Cache('/tmp/cache')

In [5]: u = uuid.uuid4()

In [6]: cache[str(u)] = 'test'

In [7]: cache[str(u)]
Out[7]: 'test'
```

**Comment by jinserk** [comment]
Sounds great! Thank you a lot!!
