### ISSUE TITLE
py36/py37: ValueError: pickle protocol must be <= 4

### ISSUE THREAD

**Issue by ssbarnea** [grantjenks/python-diskcache#206]
I observed that on py36/py37 I get an an error from within Cache, one that does not happen with py38/py39:

```
    self.cache.set("actions", _actions, expire=3600 * 24)
  File "/Users/ssbarnea/.pyenv/versions/3.7.7/lib/python3.7/site-packages/diskcache/core.py", line 775, in set
    size, mode, filename, db_value = self._disk.store(value, read, key=key)
  File "/Users/ssbarnea/.pyenv/versions/3.7.7/lib/python3.7/site-packages/diskcache/core.py", line 241, in store
    result = pickle.dumps(value, protocol=self.pickle_protocol)
ValueError: pickle protocol must be <= 4
```

This is because the initial cache was created with a different version of python, something that should not have happened. I think that this error should be detected and cache should be recreated as I doubt it would happen very often in production (same tools being run with multiple version of python on the same host).

Still current behavior also means that if you upgrade the tool and change python version, you endup being unable to start.

**Comment by grantjenks** [comment]
By default, Disk Cache uses the highest pickle protocol available. If you need Disk Cache to work across Python versions then you’ll need to set the “disk pickle protocol” to something available in the earlier versions of Python used.

See http://www.grantjenks.com/docs/diskcache/tutorial.html#settings

Given the many possible backward incompatibilities between Python versions and the custom Disks possible, I don’t think there’s a generic way to catch this scenario.

**Comment by ssbarnea** [comment]
Thank for explaining it. In case this may prove useful to others, I ended up using a hash that includes the python version, so the cache from one version would not affect another one. https://github.com/pycontribs/mk/blob/main/src/mk/runner.py#L33-L35 -- this approach should be future proof, even if new protocol is introduced by never versions.

**Comment by grantjenks** [comment]
That looks fine to me. You might also consider using a different Disk, like JSONDisk which would be able to de-serialize across Python versions.
