### ISSUE TITLE
Using DiskCache without Django dependency?

### ISSUE THREAD

**Issue by deeplook** [grantjenks/python-diskcache#211]
I see Django as a hard dependency for this package in `requirements.txt` and wonder if/why this is a must? I would like to use this without larger dependencies and I'm pretty sure Django is one of these. But then I see only few files referencing it: https://github.com/grantjenks/python-diskcache/search?l=Python&q=django. Is there an option to use this without Django?

Also, I can imagine others wanting to use DC with Django, but other versions than the one in the requirements, and there seem to be tickets for this, too. Any feedback highly appreciated.

**Comment by deeplook** [comment]
Oh, maybe it's not even imported with a normal install if I look at this: https://github.com/grantjenks/python-diskcache/blob/d9b9d06614a41beff9ebce9b1bc8038d5540394e/setup.py#L38... Well, if you want to add a one-line comment, before closing it, fine. ;)

**Comment by grantjenks** [comment]
Django is entirely optional. The “install requires” in setup.py is empty. There are no hard dependencies. Requirements.txt is only for development of the library itself.
