### ISSUE TITLE
Cache subclasses, type annotations

### ISSUE THREAD

**Issue by deeplook** [grantjenks/python-diskcache#213]
I need to provide type annotations in my code and find that when passing a cache object around it would be nice to indicate one base class for a cache, but because `Cache`, `FanoutCache` and `DjangoCache` are not subclasses of one same class I need to provide a type annotation like `cache: Union[Cache, FanoutCache, DjangoCache]` and change my code in case there will be another type of cache in the future.

I realize this is not something to change quickly. But in general it would be nice to have type annotations added to this code, too, if only because then it might be easier to do.

**Comment by grantjenks** [comment]
Can’t you just indicate a new type like: “DiskCache = Union[Cache, FanoutCache, DjangoCache]” and then use “DiskCache” for your annotations?

Another idea would be to introduce a type “Protocol” and use that as your annotation. The three caches that are currently unioned are different in some subtle ways so a Protocol seems like a better explicit way to describe the functionality that is supported.

**Comment by deeplook** [comment]
Yes, I can define a `DiskCache` as a union myself, but I'll have to update it in case you come up with a new cache type as described above. I haven't looked close enough to the differences between the three classes, though.

**Comment by heinrichreimer** [comment]
Would be fantastic to have the Protocol be part of the package itself to facilitate type checks!
Ideally, the `diskcache` library could include type annotations for all interfaces and then declare itself as a [PEP 561 compliant stub package](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages).
