### ISSUE TITLE
Excluding callable from keys with @cache.memoize() decorator?

### ISSUE THREAD

**Issue by deeplook** [grantjenks/python-diskcache#214]
When I use the convenient `@cache.memoize()` decorator the decorated callable becomes the first part of all cache keys. When I want to manually access cache items by key this is kind of annoying at least in my case, because I don't care about this part, but maybe it makes perfect sense in others. The question would be if there is a simple way of getting rid of this first key component, ideally by a parameter like in `@cache.memoize(..., ignore_callable=True)`?

**Comment by grantjenks** [comment]
I don’t think it’s so generically common as to warrant a parameter. For context, this is the first time I’ve seen an ask like it.

Note that the first value is simply a string with the full name of the function. It’s not a reference to the function object itself.

Seems generically useful to maybe be able to customize the hash function. But you can do that already by changing “func.__cache_key__” on the memoized function. You could just call the original key function and then slice the first value away.
