### ISSUE TITLE
sqllite database error: file is encrypted or is not a database

### ISSUE THREAD

**Issue by saloni10** [grantjenks/python-diskcache#218]
I’m using diskcache as a persistent cache on a shared drive(nfs based) for 3 hosts. 
I am getting the database error - file is encrypted or is not a database.
I read that sqllite is not recommended for nfs based storage ([Another issue](https://githubmemory.com/repo/grantjenks/python-diskcache/issues/164)  )  however nfs version 3 and 4 do support locking in sqllite:[Stackoverflow: Sqllite and Nfs](https://stackoverflow.com/questions/52378361/which-nfs-implementation-is-safe-for-sqlite-database-accessed-by-multiple-proces) 
I haven’t seen database is malformed error so, I’m assuming it’s okay to use nfs and sqllite.
I am looking to solve the sqllite database error.
I’m not very experienced with sqllite and python. 
Any help is much appreciated.

**Comment by grantjenks** [comment]
NFS isn't recommended https://www.sqlite.org/faq.html#q5 Sorry, I have no experience with NFS.
