### ISSUE TITLE
how to get the expire for item?

### ISSUE THREAD

**Issue by guzuomuse** [grantjenks/python-diskcache#221]
```
cache=Cache('tmp')
cache.set('item1','value1',expire=3600)
```

how cound get the setting:expire(3600) for the item1? 
or further more: get the expire time in the datetime format '2021-08-20 17:30:08'?

**Comment by grantjenks** [comment]
Use cache.get and pass expire_time=True. That’ll give the time in seconds since epoch. You’ll need to convert it to a date time after that.

The original 3600 isn’t recorded in the cache. Only the time that the item expires. If you need the 3600 recorded, use a tag.
