### ISSUE TITLE
Key retrieval check : direct and indirect    issue

### ISSUE THREAD

**Issue by arita37** [grantjenks/python-diskcache#225]
For some strange reasons the check of keys,
(and value retrieval)
seem having issues with lnt64bits keys.

Is can be related to previously corrupted disk cache ? 

```
    import diskcache as dc
    db_path = "/mydb.db"
    cache = dc.Cache(db_path, size_limit= int(100* 10**9) )
    print('Cache size/limit', len(cache), cache.size_limit ) 

   #### Insert a lot
   for in in range(5*10**9, 5*10**9 + 150500 )
      cache[i] =   str(i) + "a" * 100

    #### Get all keys
    v = cache._sql('SELECT key FROM Cache').fetchall()
    v = [ t[0] for t in v]
    
   #### Checking the keys
    key = 5*10**9 + 1000
    print(  key in v)     #### True  : OK good
   
    #### String
    print(key in cache)   ### False   !!!!!!



```

With this code, I could retrieve the key,value (!!!!):
```   
    ss = 'SELECT key,value FROM Cache WHERE key={key} LIMIT 1'
 
    for ii, k in enumerate(llist) :     
       v = cache._sql( ss.format(key= k) ).fetchall()
       print(str(v)[:100])
```

**Comment by grantjenks** [comment]
No repro for me.
```
In [7]: %run ~/scratch.py
Cache size/limit 0 100000000000
Inserting
Loading keys
Checking keys
True
Checking cache
True
```

**Comment by arita37** [comment]
Is this may due to corrupted cache file ?
(ie program crashed during insert and
make the cache in wrong state) ?

**Comment by grantjenks** [comment]
Seems unlikely to me. Each insert is done in a separate transactions and SQLite is very good at resisting corruption.

I suppose it's possible but I don't know how.

**Comment by arita37** [comment]
Thanks you.
Jus thinking in which possible cases
Where
   The direct SQL works.
   and “ key in cache” does not work .

Data type conversion ? (My key is  int64).
Wrong state somewhere ?
