### ISSUE TITLE
DjangoCache: iter keys

### ISSUE THREAD

**Issue by hottwaj** [grantjenks/python-diskcache#229]
Hi there, would you be open to adding `__iter__` or `iterkeys` to the DjangoCache API?  

Currently the keys in the cache can be iterated using (where cache is an instance of DjangoCache):

```
for key in cache._cache:
   ...
```

I can submit a PR if you are OK with adding this - let me know if you have a preference for `__iter__` or `iterkeys`.

Thanks for the nice library!

**Comment by grantjenks** [comment]
Yeah, sounds reasonable.

**Comment by grantjenks** [comment]
My preference would be for the DjangoCache API to use the `FanoutCache.__iter__` API.

Pull request welcome.
