### ISSUE TITLE
django setting to enable stats without having to call cache.stats(enable=True)

### ISSUE THREAD

**Issue by hottwaj** [grantjenks/python-diskcache#230]
Hope this is clear from the title :)

**Comment by grantjenks** [comment]
Just set `statistics` to `True`. See the Settings section at http://www.grantjenks.com/docs/diskcache/tutorial.html#settings and the DjangoCache section at http://www.grantjenks.com/docs/diskcache/tutorial.html#djangocache (note the `OPTIONS` dictionary).

**Comment by hottwaj** [comment]
Noted and sorry for missing that, thanks!
