### ISSUE TITLE
Support Django 4.0 Async Cache

### ISSUE THREAD

**Issue by Archmonger** [grantjenks/python-diskcache#231]
Django is adding an [async API](https://docs.djangoproject.com/en/dev/releases/4.0/#cache) for the cache backend.

Hopefully diskcache can add support for this.

**Comment by grantjenks** [comment]
I'm not sure it makes sense to do so except as a facade. The underlying [sqlite3 module](https://docs.python.org/3/library/sqlite3.html) doesn't support async so it can only be faked. I doubt the sqlite3 module would ever support async since there are no network calls involved with SQLite. Maybe something async would be possible based on the file IO.

Quick Google search shows https://stackoverflow.com/questions/34699948/does-asyncio-supports-asynchronous-i-o-for-file-operations regarding async file IO. Looks like threads will be the most likely route.

**Comment by grantjenks** [comment]
Probably can just use https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor with the current synchronous api. Maybe Django will do this automatically.

**Comment by grantjenks** [comment]
Looks like Django already does the sensible thing: https://github.com/django/django/blob/main/django/core/cache/backends/base.py#L145 It'll work out-of-the-box!

**Comment by Archmonger** [comment]
Look's like Django's built-in implementation uses `thread_sensitive=True`. It might be possible for diskcache to get away with `False` on that.

It's been explained to me by Goodwin that the main reasoning behind thread sensitive is that the `sqlite3` module doesn't allow switching threads between the initial caller and the executor (ex. a query lazily started in middleware then executed in a view).

Unlike Django ORM calls, diskcache calls immediate and not lazy (as far as I know), there might be some major performance gains from turning that off.

**Comment by grantjenks** [comment]
Pull request welcome. I think it may be better to upstream a `ASYNC_THREAD_SENSITIVE` class param that could change all the `thread_sensitive` params together.

**Comment by Archmonger** [comment]
Django 4.0 was released with per-request `sync_to_async` threads, which further makes `thread_sensitive=True` less important. 

See here: https://github.com/django/django/commit/36fa071d6ebd18a61c4d7f1b5c9d17106134bd44

In the case of diskcache, `thread_sensitive` can definitely be safely disabled on `django==4.0`

**Comment by Archmonger** [comment]
I received some additional clarification from the Django team.

Based on a reply from carltongibson, if I'm interpreting [his response](https://github.com/django/channels/issues/1587#issuecomment-990908898) correctly, then it's the `thread_sensitive` parameter that now pins the `sync_to_async` call to a request specific thread. So the performance difference between `True` or `False` is now negligible.

Closing this issue and PR as a result.
