### ISSUE TITLE
Minor/Patch release planned?

### ISSUE THREAD

**Issue by kai-tub** [grantjenks/python-diskcache#232]
Thank you for providing such an awesome library!
I was wondering if there is a general roadmap that indicates when the release is roughly scheduled.
I depend upon the changes of the `Stop using ENOVAL in args_to_key()` commit.
For local testing I am happy to install it with `pip -e git ...` but I'd like to release my project to PyPi and a "real" release is a lot easier to integrate.

Asking out of curiosity. :)
I do not expect to _force_ a release.

Thanks!

**Comment by Spenhouet** [comment]
I wanted to use the ignore argument of memoize which is in the documentation but not in the latest release.
The last release is quite old. Will there be a new release soon?

**Comment by grantjenks** [comment]
Oops, sorry about the documentation mismatch.

I plan to release soon (before the end of the year). Might get to it Monday.

**Comment by grantjenks** [comment]
v5.3.0 released today
