### ISSUE TITLE
use __hash__ in core.put?

### ISSUE THREAD

**Issue by zhangyingmath** [grantjenks/python-diskcache#233]
I am using memoize on a function where the input argument are large-ish (big objects). It seems in line 161, core.py, this line could cost me milliseconds: 
```
data = pickle.dumps(key, protocol=self.pickle_protocol)
```
I wonder if we can do this:
```
if hasattr(key, "__hash__"):
    dump_data = key.__hash__()
else:
    dump_data = key
data = pickle.dumps(dump_data, protocol=self.pickle_protocol)
```
One use case is that I can provide an object where I have customized `__hash__`. (I am thinking of a wrapped version of a pandas dataframe where I only care about certain things in `__hash__` and bearing the risk of having a bad representation myself.)

Of course, I am not tied to `__hash__`. Any other way to let the user provide a customized way to "hash" his input variables would be good.

**Comment by grantjenks** [comment]
See #8 . I think you might benefit from joblib

**Comment by grantjenks** [comment]
If you want to stick with diskcache then another option is to change the func’s __cache_key__ attribute. See https://github.com/grantjenks/python-diskcache/blob/20f1d93a6e3852bac4289cb94e27585d9c23330c/diskcache/core.py#L1797 in the source for how that’s use. The cache key attribute is used to transform the function arguments into a cache key. If that were changed then it could do the hashing like you describe or steal the similar hashing patterns in joblib.

**Comment by zhangyingmath** [comment]
Thanks @grantjenks ! I just realized that the built-in hash in python is not necessarily stable from session to session. So maybe what I had in mind was not a good idea, because (outside my customized objects) it might do harm in general (if we want persistency in disk). I will think about the options you mentioned and let you know how it goes.

**Comment by grantjenks** [comment]
Correct. The “hash” in Python defaults to the pointer location of the object in memory. Some types override that behavior (like strings and ints) but numpy arrays may not.
