### ISSUE TITLE
Trying to add more metadata to cache database.

### ISSUE THREAD

**Issue by bobbintb** [grantjenks/python-diskcache#234]
I'm not terribly familiar with many of the caching concept used so I am having a bit of trouble implementing this. I am working on an app that works as a daemon and requires more metadata than what the above code provides. I managed to get a simple persistent database working with the following:

`import diskcache
import os

cache = diskcache.Index('./index')

root = 'C:\\Users\\Admin\\Downloads'
for dirpath, dirnames, filenames in os.walk(root, topdown=True):
    for name in dirnames + filenames:
        path = os.path.join(dirpath, name)
        cache[path] = os.stat(path)`

I will need most of what `os.stat` returns but the above code doesn't use it all. From what I've been reading, Index is what I should be using, so I think I've got a good start. Is there a way to change or extend the schema for the db? I spent the last day pouring over the docs and tutorials and haven't gotten anywhere. I'd appreciate any help. Thanks.

**Comment by grantjenks** [comment]
No, diskcache is a simple key-value store. There is no way to “extend the schema”.

For a local relational database, use SQLite.
