### ISSUE TITLE
DuckDB column-oriented integration?

### ISSUE THREAD

**Issue by vackosar** [grantjenks/python-diskcache#236]
It seems that it would reduce storage requirements by caching vectors in DuckDB. Would it make sense to integrate DiskCache with DuckDB which has similar API to Sqlite?

**Comment by grantjenks** [comment]
Probably not. DickDB does best when answering analytics queries and is not as transactionally oriented. DiskCache doesn’t have any APIs for analytics queries and relies very heavily on transactions.

I thinknDuckDB is a great looking project but it’s unlikely to fit diskcache well.
