### ISSUE TITLE
Limit on expire keyword!

### ISSUE THREAD

**Issue by Satish1536** [grantjenks/python-diskcache#237]
Hey,

Is there any limit on the value of expire keyword in the set function? Or is it just depend on the resources we have or how frequently we need the updated information.

```
from diskcache import Cache
cache = Cache('temp_cache')

mId = f'Id{id}'
data = cache.get(mId)

if data is None:
    with Cache(cache.directory) as reference:
        reference.set(mId, data, expire=400)
```
Above is the code snippet where I want to increase the expire value from 400 seconds to 2 - 5 days. Is it possible or will there be any issue due to that?

**Comment by grantjenks** [comment]
There’s nothing wrong with a longer expire parameter. It’s also possible to use None to disable expiration. http://www.grantjenks.com/docs/diskcache/api.html#diskcache.Cache.set
