### ISSUE TITLE
Cache count under Linux maybe not working?

### ISSUE THREAD

**Issue by screig** [grantjenks/python-diskcache#242]
Hi

I have a library that uses diskcache, I test this, in-house, through Gitlab under both Windows and Linux, I am running the same tests on both systems. On tearing down the test I log the cache details. So here under windows, you can see the size and count of the cache.

![image](https://user-images.githubusercontent.com/4292074/146161199-265acca1-6814-4cbf-9e7a-66a4b31e960f.png)

When I execute the same test in Linux I get the following:

![image](https://user-images.githubusercontent.com/4292074/146161323-c232e4db-b7d0-48c7-9664-174de1813089.png)

So the size is the same but the count is zero? 

![image](https://user-images.githubusercontent.com/4292074/146161453-fb77ef5b-5c32-409f-9ab0-cbbd4cecebc0.png)

I know that the cache is not empty as I also run some test to extract data from the cache. I wonder if this is a bug?

Thanks
Sean

**Comment by grantjenks** [comment]
Can you double check the version used on both platforms? Print `diskcache.__version__`

The “count” attribute should be lazily recomputed. Can you check the output of `len(cache)` instead?

**Comment by screig** [comment]
Thanks for the quick reply

![image](https://user-images.githubusercontent.com/4292074/146231840-178a5913-b358-4200-90e8-6dd1f09d10fa.png)


diskcache                     5.3.0  (from pip list)
![image](https://user-images.githubusercontent.com/4292074/146231547-a241db78-ac89-4cc0-ae60-cf801023f489.png)


diskcache                     5.3.0  (from pip list)
![image](https://user-images.githubusercontent.com/4292074/146231671-0f6949e2-3fcd-4481-bd7c-a6c5d627220b.png)

Works this time (how odd), so please close this.

Thanks again
