### ISSUE TITLE
Nested Attributes not getting Updated

### ISSUE THREAD

**Issue by darthShadow** [grantjenks/python-diskcache#245]
Hi,

First of all, thanks for the wonderful library.

I am facing an issue when updating nested attributes of an index:

```py
In [1]: from diskcache import Index

In [2]: cache = Index("/tmp/cache")

In [3]: list(cache.items())
Out[3]: []

In [4]: cache['a'] = {'b': "1"}

In [5]: list(cache.items())
Out[5]: [('a', {'b': '1'})]

In [6]: cache['a']['b']
Out[6]: '1'

In [7]: cache['a']['b'] = "2"  # This doesn't work

In [8]: cache['a']['b']
Out[8]: '1'

In [9]: cache['a']
Out[9]: {'b': '1'}

In [10]: cache['a'] = {'b': "2"}  # This works

In [11]: cache['a']['b']
Out[11]: '2'

In [12]: cache['a']
Out[12]: {'b': '2'}
```

Is this the expected behaviour due to the semantics of the underlying structures or is there a bug here?

Thanks.

**Comment by grantjenks** [comment]
That’s expected. DiskCache can’t detect changes to nested attributes.

For reference, read about the Python Data Model at https://docs.python.org/3/reference/datamodel.html DiskCache is using the getitem and setitem operator methods.
