### ISSUE TITLE
The functionality to remove cache files, removes all files under cache directory.

### ISSUE THREAD

**Issue by salman0149** [grantjenks/python-diskcache#247]
shutil.rmtree(cache.directory) , will remove all files under cache.directory, if we specify a generic directory , there may be some files not related to cache. Would like a seperate interface which can act up to clean up only cache files.

**Comment by grantjenks** [comment]
`Cache.clear` doesn't use `shutil.rmtree(directory)`. Are you sure DiskCache removed the directory?

**Comment by salman0149** [comment]
I am checking the guide which mentions : - _Caches do not automatically remove the underlying directory where keys and values are stored. The cache is intended to be persistent and so must be deleted manually._

Here if i give a generic directory where other data is stored , all files will get deleted by calling shutil.rmtree, i can write a logic to filter the files and delete , but it will be good if there is an interface to do it.

**Comment by grantjenks** [comment]
If you want it to persist then don’t delete it.

If you want to remove all trace of it then use a sub dir and recursively delete the sub dir with rmtree.

By default a temporary directory is created which is guaranteed to be shared with no other dir.

**Comment by salman0149** [comment]
OK , got it , thanks .
