### ISSUE TITLE
Portable cache windows / linux

### ISSUE THREAD

**Issue by audetto** [grantjenks/python-diskcache#248]
DiskCache writes the path in the database using OS specific path separators.

If I generate a cache on Windows and try to use it on linux, it cannot find the files.

would it make sense to use '/' as a path separator everywhere?

**Comment by grantjenks** [comment]
I think using the “/“ everywhere could break support on Windows as that’s the purpose of os.path.join which is used by DiskCache.

To change what’s used in the filenames, create a custom disk. The filename is generated in the filename() method of the Disk class at https://github.com/grantjenks/python-diskcache/blob/1cb1425b1ba24f26fb1e37349c4c2658c2a46d8f/diskcache/core.py#L287 Inherit from Disk, overrode the method, and use the derived class in the Cache initializer.

See the docs, source, and tests for an example using JSONDisk.

**Comment by audetto** [comment]
Windows accepts both / and \ even when mixed in the same path.

I will use the Disk. Thank you.
