### ISSUE TITLE
Some random crash with a fanout cache

### ISSUE THREAD

**Issue by pombredanne** [grantjenks/python-diskcache#25]
I get this error but this kinda random. Only found on python 2.7.3 on Linux/Ubuntu 12.04.

You can see the code calling it here:
https://github.com/nexB/scancode-toolkit/blob/0030a717f8f202b24aa6943f4d62d66a627fd047/src/licensedcode/cache.py#L148

```
[...]
 File "/home/pombreda/scancode-toolkit/src/licensedcode/cache.py", line 171, in get
   cached = self.cache.get(cache_key)
 File "/home/pombreda/scancode-toolkit/local/lib/python2.7/site-packages/diskcache/fanout.py", line 84, in get
   default=default, read=read, expire_time=expire_time, tag=tag,
 File "/home/pombreda/scancode-toolkit/local/lib/python2.7/site-packages/diskcache/core.py", line 664, in get
   value = self._disk.fetch(self._dir, mode, filename, db_value, read)
 File "/home/pombreda/scancode-toolkit/local/lib/python2.7/site-packages/diskcache/core.py", line 245, in fetch
   return pickle.load(io.BytesIO(value))
TypeError: 'buffer' does not have the buffer interface

```

I am using 1.6.6 
https://github.com/nexB/scancode-toolkit/blob/0030a717f8f202b24aa6943f4d62d66a627fd047/thirdparty/prod/diskcache.ABOUT

**Comment by pombredanne** [comment]
Actually based on this patch to some code experiencing the same issue, the problem can likely be fixed in diskcache here: See https://www.cubicweb.org/revision/10692445
The bug is this: http://bugs.python.org/issue10211
And gist of their solution is:
```
6 -from io import BytesIO
7 +if (2, 7) <= sys.version_info < (2, 7, 4):
8 +    # http://bugs.python.org/issue10211
9 +    from StringIO import StringIO as BytesIO
10 +else:
11 +    from io import BytesIO
```

**Comment by balusarakesh** [comment]
I just tested the code and it seems to work fine.

**Comment by pombredanne** [comment]
@grantjenks pr #26 is there for your review

**Comment by grantjenks** [comment]
Thanks. I will merge and deploy later today.

**Comment by grantjenks** [comment]
Deployed at v1.7.0 to PyPI.

**Comment by pombredanne** [comment]
@grantjenks You rock!
