### ISSUE TITLE
Should cache be closed or not?

### ISSUE THREAD

**Issue by gherkz** [grantjenks/python-diskcache#253]
I was reading the [tutorial](https://grantjenks.com/docs/diskcache/tutorial.html) for diskcache and found this section a little bit confusing:

> Each thread that accesses a cache should also call [close](https://grantjenks.com/docs/diskcache/api.html#diskcache.Cache.close) on the cache. Cache objects can be used in a with statement to safeguard calling close.
> 
> ```
> cache.close()
> with Cache(cache.directory) as reference:
>     reference.set('key', 'value')
> True
> ```
> 
> Closed Cache objects will automatically re-open when accessed. But opening Cache objects is relatively slow, and since all operations are atomic, may be safely left open.
> 
> ```
> cache.[close](https://grantjenks.com/docs/diskcache/api.html#diskcache.Cache.close)()
> cache.get('key')  # Automatically opens, but slower.
> 'value'
> ```

The first part says "Each thread that accesses a cache should also call close".

The second part says "But opening Cache objects is relatively slow, and since all operations are atomic, may be safely left open".

Should I be closing the cache object, or can it safely be left open?

**Comment by grantjenks** [comment]
If you’re worried about running out of file handles, then every thread must close the cache after using it to release the resources.

But you’re probably not worried about running out of file handles, so just leave the cache open.

**Comment by gherkz** [comment]
Thank you for the quick response. I've just finished integrating diskcache into a new microservice, and it was super-easy to set up and appears to be working great so far. Keep up the good work 🙂
