### ISSUE TITLE
It would be nice to provide an in-memory METADATA/statistics

### ISSUE THREAD

**Issue by mayli** [grantjenks/python-diskcache#255]
I can add a quick patch to provide an in-memory `.cache_info()` for `Cache`, which is similar with `functools.lru_cache.cache_info()`.
Do you think it's helpful to have it in the upstream?

**Comment by grantjenks** [comment]
It’s already there under the name “stats”: https://grantjenks.com/docs/diskcache/api.html#diskcache.Cache.stats

**Comment by mayli** [comment]
> It’s already there under the name “stats”: https://grantjenks.com/docs/diskcache/api.html#diskcache.Cache.stats

The issue of that is each read operation will turns into a write to be persisted into sqlite, the in-memory idea is to avoid that overhead, while having some rough idea of cache hits/misses.

**Comment by grantjenks** [comment]
I’m not a fan as it would only work within the same process. Stats() works across processes
