### ISSUE TITLE
Losing key/value pairs after time=???

### ISSUE THREAD

**Issue by smprather** [grantjenks/python-diskcache#256]
Hi DiskCache--

Q1: Since this is likely user-error, is there a forum to ask questions? I couldn't find one.

Q2: If A1==False:
I have a problem with my cache "losing" key/value pairs after some period of time even though I'm setting expire=None.

```python
# Poor-man's md5sum
lib_file_cache_key = str(self.lib_file.resolve()) + str(os.path.getsize(self.lib_file))
cache.set(lib_file_cache_key, self.lib, expire=None)
```

If I run my script in quick succession (or within and hour, or within time=??), then I get a cache hit. But when I return to my desk each day, the key/value pairs are gone, and the value must be recalculated (very time consuming parse of the Liberty file format we use in EE). Any idea what I'm doing wrong? [Note: The cache dir is on an NFS project disk. Not any kind of /tmp volatile.]

Thanks!
--Myles

**Comment by avin3sh** [comment]
I am also seeing this behavior and I also do read and writes on the Cache in quick succession, sometimes the data isn't lost for many days, other times it happens daily or even multiple times in a day, usually co-related with frequency of reads and writes. Is FanoutCache recommended for such cases ?

**Comment by smprather** [comment]
I was caching some big pickle files, so I probably ran into the limit. I ditched diskcache and worked around it with my own simple caching scheme. But this is good to know for the future. Thanks Grant!
