### ISSUE TITLE
[Feature Request] Support dill

### ISSUE THREAD

**Issue by schmoelder** [grantjenks/python-diskcache#259]
Due to the standard library's limitation to serialize many data types using `pickle`, I unfortunately cannot currently use `python-diskcache` in my research.

[Dill](https://github.com/uqfoundation/dill) is a python library which expands python's pickle module for serializing and de-serializing to the majority of the built-in python types including lambda functions.

I understand that python-diskcache is pure python only but since `dill` provides the user the same interface as the `pickle`, making it optional could be an option. All that would be required would be ` import dill as pickle`. See also a working prototype: https://github.com/schmoelder/python-diskcache/tree/support_dill

**Comment by grantjenks** [comment]
Create a custom Disk data type. See the docs at https://grantjenks.com/docs/diskcache/tutorial.html#disk

**Comment by schmoelder** [comment]
Ok, thanks for the tip! It's quite a bit of boilerplate in comparison but seems to work.
