### ISSUE TITLE
Cache __init__ is not thread/process safe

### ISSUE THREAD

**Issue by f3flight** [grantjenks/python-diskcache#266]
When `Cache` object is concurrently instantiated in several threads or processes with the same cache path, `sqlite.DatabaseError` may occur. As the library claims to be thread and process safe, I think this claim should extend to the init stage as well. One possible solution is to use a filesystem-based lock for the init function.

**Comment by grantjenks** [comment]
Can you post a repro? I’d like to test on different machines. My concern is that the issue exists lower than diskcache either in the sqlite3 module or sqlite source code itself. There are a number of pragmas executed during initialization which may create process safety issues.

**Comment by grantjenks** [comment]
Also, would you include the error message with the exception? If the database is corrupted then that’s more suspicious that maybe something strange is configured on the host that is executing.

**Comment by f3flight** [comment]
You may be right as I cannot reproduce the exact error. Here's my attempt:

```
#!/usr/bin/env python3

import os
import random
import shutil
from diskcache import Cache
from time import sleep
from threading import Thread


def use_cache():
    sleep(random.random()/100)
    try:
        cache = Cache('tempdir')
    except Exception as e:
        print(f'init - {e}')
    try:
        cache.add(key='blah', value=b'1'*random.randint(0, 1000000))
    except Exception as e:
        print(f'add - {e}')

if os.path.exists('tmpdir'):
    shutil.rmtree('tmpdir')

threads = []
for i in range(400):
    threads.append(Thread(target=use_cache))
    threads[i].start()

for thread in threads:
    thread.join()
```

I get "database is locked" printed with this code. Not exactly what I was aiming for.
I'm not going to pursue the repro further as we have a workaround which is to synchronize and cache the call to `Cache` itself, mainly wanted to have a record of this issue.

**Comment by f3flight** [comment]
For the record, the original exception looked like this:
```
  File "site-packages/diskcache/core.py", line 456, in __init__
    sql = self._sql_retry
  File "site-packages/diskcache/core.py", line 652, in _sql_retry
    sql = self._sql
  File "site-packages/diskcache/core.py", line 648, in _sql
    return self._con.execute
  File "site-packages/diskcache/core.py", line 636, in _con
    settings = con.execute(select).fetchall()
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by grantjenks** [comment]
I'm not able to reproduce the issue. I think the issue exists lower than diskcache either in the sqlite3 module or sqlite source code itself.
