### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'type_str'

### ISSUE THREAD

**Issue by WyseNynja** [grantjenks/python-diskcache#267]
diskcache works for me in some parts of my code, but in another I'm getting a confusing error

```
from diskcache import Cache

disk_cache = Cache(Path.home() / ".cache/flashprofits/diskcache")
```

```
Traceback (most recent call last):
  File "/flashprofits/flashprofits/debug_helpers.py", line 165, in make_transaction_traceable
    cached_tx = disk_cache.get(cache_key)
  File "/venv/lib/python3.9/site-packages/diskcache/core.py", line 1173, in get
    value = self._disk.fetch(mode, filename, db_value, read)
  File "/venv/lib/python3.9/site-packages/diskcache/core.py", line 283, in fetch
    return pickle.load(reader)
TypeError: __new__() missing 1 required positional argument: 'type_str'
```

When the cache lookup fails, my code keeps going. I'd like to save a bunch of time reading from the cache. Any idea what this error means?

**Comment by grantjenks** [comment]
I didn't think the "Path() type" was supported. You'll need to convert to str() first. See #250

**Comment by WyseNynja** [comment]
Thanks for the rapid response!

Unfortunately, changing my code to `disk_cache = str(Cache(Path.home() / ".cache/flashprofits/diskcache"))` did not change the error.

**Comment by grantjenks** [comment]
Judging from the traceback:
```
Traceback (most recent call last):
  File "/flashprofits/flashprofits/debug_helpers.py", line 165, in make_transaction_traceable
    cached_tx = disk_cache.get(cache_key)
  File "/venv/lib/python3.9/site-packages/diskcache/core.py", line 1173, in get
    value = self._disk.fetch(mode, filename, db_value, read)
  File "/venv/lib/python3.9/site-packages/diskcache/core.py", line 283, in fetch
    return pickle.load(reader)
TypeError: __new__() missing 1 required positional argument: 'type_str'
```
You're calling "Cache.get()" which calls "Disk.fetch()" which calls "pickle.load()" so I'd guess you're trying to unpickle a value which cannot do so. It's strange that the error didn't occur when the object was stored. Trying pickling the value yourself.

**Comment by WyseNynja** [comment]
I think some threading objects made it into the pickled values and those make pickle.load unhappy. My current code overwrites those unsafe objects with True/False but there must have been a time when it didn't do that. I agree that it's strange I didn't see the error while storing them.

I just cleared my caches and am re-running my script (it takes a while to run). Will play with this more tomorrow.

Thank you for your help!

**Comment by grantjenks** [comment]
Stale.
