### ISSUE TITLE
memoize(typed=True) with JSONDisk fails 

### ISSUE THREAD

**Issue by indigoviolet** [grantjenks/python-diskcache#274]
https://github.com/grantjenks/python-diskcache/blob/master/diskcache/core.py#L410

passes the type of the argument into the cache key, but `json.dumps(type(arg))` will fail since `TypeError: Object of type type is not JSON serializable`.

Is this expected?

**Comment by indigoviolet** [comment]
You may want to try `jsonpickle` instead.

**Comment by grantjenks** [comment]
Yes, that’s expected. Not all disks/serializers support all types.
