### ISSUE TITLE
Memoize decorate will remove the type hint of the original function

### ISSUE THREAD

**Issue by MacHu-GWU** [grantjenks/python-diskcache#276]
If you put Cache.memoize on a custom function, you will lose the type hint when using that function

```
from diskcache import Cache

cache = Cache(directory=...)

@cache.memorize
def hello(name: str):
    return f"hello {name}"

hello(...) # when you type this, you won't see name as argument in VSCode PyCharm etc ...
```

**Comment by MacHu-GWU** [comment]
@grantjenks thank you for the great work!

I found an issue and also send a PR to fix it. Wish I could contribute a little

#277

**Comment by grantjenks** [comment]
Let’s discuss in the PR.

**Comment by phi-friday** [comment]
Using [`diskcache-stubs`](https://github.com/phi-friday/diskcache-stubs) solves this problem.
I have confirmed that it works for `pyright`,
For `mypy`, I have confirmed that it works in the latest commit (which will be deployed in a new release soon).

##### arg types
![스크린샷 2024-05-16 오후 3 42 43](https://github.com/grantjenks/python-diskcache/assets/19867547/ad25eab8-0ea0-445f-8b0f-6dfa506caa75)

##### `__cache_key__`
![스크린샷 2024-05-16 오후 3 43 02](https://github.com/grantjenks/python-diskcache/assets/19867547/adde2647-ecf6-4ff9-abf2-7e80689490dd)
