### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by haichii** [grantjenks/python-diskcache#279]
I tried this [examples](https://dash.plotly.com/background-callbacks) of plotly dash, but I get this error and cannot proceed. 
I am a newbie so I don't know if it is a problem with my computer or something else. I am using windows 10 and this example works fine on other PCs (windows10 & macbook pro). I created a virtual environment with anaconda and use visual studio code.

- Python 3.10.10
- I installed the necessary libraries with pip and did not specify a version

The error is 
`settings = con.execute(select).fetchall()`
`sqlite3.DatabaseError: database disk image is malformed`

I've already read [this](https://github.com/grantjenks/python-diskcache/issues/67) and tried to figure out but it didn't work.

**Comment by grantjenks** [comment]
That's not a lot to go on 🤷‍♂️ 

Do any of the caveats apply https://grantjenks.com/docs/diskcache/tutorial.html#caveats ? These are usually file system issues. Windows Subsystem for Linux sometimes also causes issues.

**Comment by haichii** [comment]
Thank you for your early response and sorry for wasting your time.
I copied a file and tried to run so it didn't work. 
I deleted a cache folder which already created and it worked!
