### ISSUE TITLE
Controlling the number of files generated by Cache

### ISSUE THREAD

**Issue by GDeLaurentis** [grantjenks/python-diskcache#283]
Hello there!

First of all, thanks a lot for the very nice library, it has been incredibly useful.

I have come across an issue while using diskcache.Cache that I couldn't find a solution for in the documentation. Apologies if I have missed this.

The problem I encountered is related to controlling the number of files generated by Cache. For instance, at present, I have a single 4GB cache with around 100k files. Unfortunately, this poses a problem on remote systems where I have a strict limit on the number of files, which is typically capped at around 1M files.

I was wondering if there is an option, similar to 'size_limit', that would allow me to put a limit on the number of files. That is, force the Cache to use fewer but larger files. If there isn't such an option currently available, I believe it would be a very useful addition for handling large databases.

Cheers,
Giuseppe

**Comment by grantjenks** [comment]
There’s no functionality for that exactly built in today.

One option is to increase the minimum disk file size to something larger or very large. By doing so, more values will be stored directly in sqlite itself and no extra files will be used.

A more complex option is to create a custom eviction scheme. This would require inheriting from Cache and implementing the logic for culling items. You would need to read through the code to understand how. One challenge in this design is knowing the number of files used. I don’t believe that’s tracked currently.

Another option would be to create a custom Disk that somehow packs files together. Maybe you could put a zip file in subdirectories and pack values together in a single zip file. No idea what the performance would be like for reads/writes with that approach.

**Comment by GDeLaurentis** [comment]
The first option you mention might be a good and easy solution for now. Is there any downside to increasing the minimum disk file size? E.g. slower current reads/writes, or more frequent corruption.

Regarding the eviction scheme, am I correct in saying that it decides how to move entries between the `*.val` and `cache.db` files? It sounds like the "none" policy would have the same effect as a very large minimum disk file size, potentially keeping everything in `cache.db`. However, it seems that changing the eviction logic would postpone the problem, but not fix it. 

I'm afraid zipping would be too slow, at least for my application.

Thanks for the clarifications.

**Comment by grantjenks** [comment]
You'll have to test your application to know the impact. Writes to files are done to reduce the time taken writing to the database. But writes don't block reads. If your writes are rare enough, it won't matter. Just measure.

Eviction does not refer to the use of files. When eviction takes place, the item is deleted from the cache entirely.
