### ISSUE TITLE
List keys?

### ISSUE THREAD

**Issue by alipunjani** [grantjenks/python-diskcache#29]
Is there a builtin way to list keys in the cache?

Right now I'm using

```
cache._sql('SELECT key FROM Cache').fetchall()
```

**Comment by grantjenks** [comment]
Iter and reversed are available on diskcache.Core from v1.7.0: https://github.com/grantjenks/python-diskcache/commit/f2abf5d6b744ea75f62fb88fe24a69d3685cbb4a

Note there's a bug: https://github.com/grantjenks/python-diskcache/issues/27

I have a number of changes to release this week or next.

**Comment by grantjenks** [comment]
Fixed and deployed in v2.0.2 on PyPI.
