### ISSUE TITLE
Pickling error, args have wrong class

### ISSUE THREAD

**Issue by mikayla-grace** [grantjenks/python-diskcache#30]
We created a simple transaction class in memory which worked great but it consumes too much heap memory so we switched to diskcache 2.0.2 with Python 3.5.  In most cases, diskcache works as expected.  However, on occasion we get a pickling exception.  Is this a bug?  Is there a workaround?  Here is the trace, notice the first relationship successfully pushes to the cache, the second one fails:

```
2016-09-24 12:03:42,371 INFO chemGraph: relationship(108494) Article-id-chem-article-10651284-[chemical]-Chemical-id-chem-chemical-thromboplastin
2016-09-24 12:03:42,461 INFO chemGraph: relationship(108495) Article-id-chem-article-10651284-[mesh]-MESH-id-umls-d008958
ERROR:root:transaction cache failed: (f0e044f)-[:mesh {id:"chem-article-10651284-umls-d008958",importDate:"2016-09-24T16:03:42.461744Z",nameHash:"chem-article-10651284-umls-d008958",source:"http://www.chemicals-r-us.info/chem",type:"article-mesh",uuid:"6de965a7-1f40-5d65-ae5a-ee7ab9723bbf"}]->(a011ffb)
Traceback (most recent call last):
  File "/chem/Fusion/ChemGraph.py", line 240, in checkTransactionLimits
    self.transaction_cache[name]=node
  File "/usr/lib/python3.5/site-packages/diskcache/core.py", line 510, in set
    size, mode, filename, db_value = self._disk.store(value, read)
  File "/usr/lib/python3.5/site-packages/diskcache/core.py", line 196, in store
    result = pickle.dumps(value, protocol=self._protocol)
_pickle.PicklingError: args[0] from __newobj__ args has the wrong class
```

Here is our diskcache initialization:

```
  from diskcache import Cache
  self.transaction_cache=Cache(cachePath+'/transaction/'+index, size_limit=MaxCacheSize)
```

**Comment by mikayla-grace** [comment]
We think we found the problem, we prematurely closed the cache in another thread.  Removing the close appears to have stopped the diskcache exceptions.

**Comment by grantjenks** [comment]
Remember to call close in each thread that uses the cache. But I do not think that would cause this error.

DiskCache uses the pickle module in the standard library. Can you test pickling `node` objects? Try something like this:

    pickle.dumps(node, protocol=3)

My guess is your object does not support pickling protocol level 3. You can change diskcache to use a lower pickling protocol with:

```
class MyDisk(diskcache.Disk):
    def __init__(self, *args, **kwargs):
        kwargs['pickle_protocol'] = 0
        super(MyDisk, self).__init__(*args, **kwargs)

cache = diskcache.Cache('/path/to/directory', disk=MyDisk)
```

**Comment by mikayla-grace** [comment]
Thank you for the quick and detailed response.  Unfortunately we get an exception:

```
  File "/chem/Fusion/chemGraph.py", line 133, in __init__
    disk=MyDisk,size_limit=MaxCacheSize)
  File "/usr/lib/python3.5/site-packages/diskcache/core.py", line 357, in __init
__
    pickle.HIGHEST_PROTOCOL,
  File "/knovo/Fusion/Nextgen/KnovoGraph.py", line 77, in __init__
    super(MyDisk, self).__init__(*args, **kwargs)
TypeError: __init__() got multiple values for argument 'pickle_protocol'
```

**Comment by grantjenks** [comment]
Sorry, try this instead:

```
In [17]: class MyDisk(diskcache.Disk):
   ....:     def __init__(self, *args, **kwargs):
   ....:         args = list(args)
   ....:         args[2] = 0  # pickle_protocol
   ....:         super(MyDisk, self).__init__(*args, **kwargs)
   ....:         

In [18]: cache = diskcache.Cache('/tmp/test', disk=MyDisk)
```

Note that pickle protocol 0 is text based and slow. Try using protocol 2 which is binary, faster, and has been around longer. I think on Python 3.5 the highest protocol is 3 which is giving you errors.

**Comment by mikayla-grace** [comment]
Protocol 2 fails.  Protocol 3 was working until the latest update of the Python 3 libraries on Fedora 24.  Also some ```node```(s) work with protocol 3 while others fail.  Reverting to protocol 0 works for all nodes.
