### ISSUE TITLE
PR for fork deadlock

### ISSUE THREAD

**Issue by arieleiz** [grantjenks/python-diskcache#300]
Hi,

Here is a PR to fix a deadlock in python-diskache when forking with the transaction lock locked:

https://github.com/grantjenks/python-diskcache/pull/299.

When a fork occurs while the sqlite db is mid-transaction, the sqlite transaction lock remains locked forever in the forkee, deadlocking it.

**Comment by grantjenks** [comment]
Closing in favor of the PR for discussion.
