### ISSUE TITLE
Promote Pickle Protocol to Cache Setting with "disk" Prefix

### ISSUE THREAD

**Issue by pombredanne** [grantjenks/python-diskcache#32]
This is likely a pickle/cPickle bug in Python 2.7 when using HIGHEST_PROTOCOL which is diskcache default. Found while working on https://github.com/nexB/scancode-toolkit/issues/267
You can see these two tests in action:
 - bare pickling issue:  https://github.com/nexB/scancode-toolkit/commit/50bfc213fd6d9d734aa6afb0dc8aa58faf3fed5a
 - same issue when using diskcache: https://github.com/nexB/scancode-toolkit/commit/6b92ccf5340637199dcfbcb4fea7685540b58e5b

The simple workaround is to avoid using  HIGHEST_PROTOCOL. I guess this can be done by passing a custom Disk subclass forced to use no specific protocol.

**Comment by grantjenks** [comment]
Yes, that looks like a bug inherited from pickle.

Another user reported problems with pickle in Issue #30.

Workaround was similar to your code: use a `Disk` subclass.

I think it would be worth promoting "pickle_protocol" to a `Cache` setting. That's already the case with the other Disk parameter: `size_threshold`. As a Cache setting, you could simply pass `pickle_protocol=2` when initializing the Cache.

**Comment by grantjenks** [comment]
Updated title: 'Promote Pickle Protocol to Cache Setting with "disk" Prefix'

Note that `large_value_threshold` should also use the "disk" prefix. Can this be done while remaining backwards compatible? I'm not sure.

**Comment by grantjenks** [comment]
Done. Deployed at 2.3.0. You can now use "disk_pickle_protocol=0" when you initialize the cache.

```
with Cache('/tmp/mycachedir', disk_pickle_protocol=0) as cache:
    pass
```

Note that I removed the "large_value_threshold" setting. So version 2.3.0 is not backwards compatible if you were using that before.
