### ISSUE TITLE
Support get_many, set_many, and delete_many Cache operations

### ISSUE THREAD

**Issue by Suor** [grantjenks/python-diskcache#45]
Helps a lot with lots of small values. My use case:
- batch queries to API
- caching calls is inefficient since sets of queries vary
- caching by each query separately makes sense

So it looks like:
```python
def _mygene_fetch(queries, specie):
    # Read cache
    cache = diskcache.Cache('/tmp/mygene-cache/' + specie, timeout=CACHE_TIMEOUT)
    res = compact({q: cache.get(q) for q in queries})

    queries = set(queries) - set(res)
    if queries:
        data = api.querymany(queries, species=specie)
        new = {item['query']: (item['entrezgene'], item['symbol'])
               for item in data}
        res.update(new)
        # Cache results
        for k, v in new.iteritems():
            cache[k] = v

    return res
```
And it's slow.

**Comment by grantjenks** [comment]
I agree this is a useful feature. Thank you for the code snippet.

**Comment by Suor** [comment]
You might want to use Django caches `.get_many()`/`.set_many()` interface, just to not add new one :)

**Comment by tamirOK** [comment]
Do get_many  and set_many operations have to hit database only once?

**Comment by Suor** [comment]
Can't see if that is important, this should obviously be more efficient than a cycle of gets or sets, but otherwise implementation could be arbitrary.

**Comment by grantjenks** [comment]
As I've thought about it, I doubt you could do ``get_many`` or ``set_many`` in a single database query but you could do them in a single database transaction. The database should be smart about which pages it updates and syncs.

So, yes, those methods should use a single database transaction.

Also, I don't think any batching should be done inside those methods. I want batching left to the end-user. If we give them an API like I've described above then the end-user can easily batch keys/values (as they may want in the case where the number of keys/values is very large). Not batching will block concurrent writers but the scenario is similar to writing a large value.

**Comment by grantjenks** [comment]
In v4, diskcache will support transactions. There will be a tutorial section on transactions that will show how to do the *-many variants in one transaction.

**Comment by grantjenks** [comment]
The ``set_many`` example was added to the Transactions section of the tutorial at 126b033

**Comment by npip99** [comment]
@grantjenks

Hello, I'm currently using the "transact" functionality, but it's still slower than batch insert:

```
set Time: 543.16ms
with transact set Time: 249.00ms
batch INSERT: 105.68ms
```

There's a lot of overhead in my test, so the ratio is probably even stronger than the above numbers imply.

Particularly on EC2 instances, for loop set() is very slow, because it's a roundtrip to the 1ms-latency SSD for each set. Meanwhile a single batch insert only incurs that latency once.
