### ISSUE TITLE
memoize not implemented on Cache

### ISSUE THREAD

**Issue by kootenpv** [grantjenks/python-diskcache#57]
```python
import diskcache
cache = diskcache.Cache("tmp")
@cache.memoize
def fn(x):
    return x
```

`AttributeError: 'Cache' object has no attribute 'memoize'`

Is there a reason it is only implemented for `FanoutCache`?

**Comment by grantjenks** [comment]
I think I wanted to avoid the TimeoutError semantics of diskcache.Cache. The timeout/retry logic really belongs in FanoutCache so if you want set-it-and-forget-it memoization then you don't want Cache.

Does that make sense?

**Comment by grantjenks** [comment]
Also the memoize logic is defined in diskcache.memo if you're curious. If there were a clever way to make the retry=True parameter optional then maybe we could apply it to diskcache.Cache as well. But even then, I think the TimeoutError is an odd caveat and too leaky as an abstraction for memoization.
