### ISSUE TITLE
Tests needed for incremental backup using rsync

### ISSUE THREAD

**Issue by elistevens** [grantjenks/python-diskcache#58]
It would be nice if incremental backup behavior were guaranteed by tests to always work.

Edit: I would like to have there be tests that check that using rsync to back up a cache dir will keep the backup up-to-date with all new content in the cache, and that only new content is synched (so that if 99% of the content is unchanged, it will only be scanned locally by rsync, and not redundantly copied).

If the backed-up copy of the cache dir is then used, it should behave identically to the original.

For our use cases we can pause all readers and writers during the course of the backup, so we're not concerned about race conditions.

**Comment by grantjenks** [comment]
Related: https://github.com/grantjenks/python-diskcache/issues/42

**Comment by grantjenks** [comment]
Committed at d0936a5. To be deployed in v3 to PyPI.
