### ISSUE TITLE
Update Django Cache Testing to Use Django v1.11

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/python-diskcache#65]
Update Django Cache Testing to Use Django v1.11

**Comment by tehfink** [comment]
And maybe for Django 2.0?

**Comment by grantjenks** [comment]
I think it's compatible with Django 2.0, but it's not tested. The API changes pretty rarely at this point.

I'd like to target 1.11 for as long as it remains in LTS.

**Comment by tehfink** [comment]
Thanks. I've been running with Django 2.0.2 & Python 3.6.4 for the past few hours. So far no issues.

**Comment by grantjenks** [comment]
Fixed at f61404d and deployed at 3.0.4
