### ISSUE TITLE
Error: Database Disk Image is Malformed

### ISSUE THREAD

**Issue by tachim** [grantjenks/python-diskcache#67]
I was using this module normally I think and ended up with `DatabaseError: database disk image is malformed` which left the whole cache unusable. Not much else to report :/

**Comment by grantjenks** [comment]
That sucks. If you have a way to reproduce the issue, I'd love to try debugging it. I've never seen that myself nor in integration tests.

Otherwise, here's some good info on recovering SQLite3 databases:

* https://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed

**Comment by tachim** [comment]
This seems to happen more often when the ipython notebook I'm using it in is killed. Does diskcache set transaction commit properties conservatively? I'm grasping for straws here, not sure what the issue would be.

**Comment by tachim** [comment]
FYI here's what happened when I repaired it:

```tudor@DL2 /data/users/tudor/width_model_cache2/000 $ echo '.dump'|sudo sqlite3 $DB_NAME| sudo sqlite3 repaired_$DB_NAME
Error: near line 20: UNIQUE constraint failed: Settings.key
Error: near line 21: UNIQUE constraint failed: Settings.key
Error: near line 22: UNIQUE constraint failed: Settings.key
Error: near line 23: UNIQUE constraint failed: Settings.key
Error: near line 24: UNIQUE constraint failed: Settings.key
Error: near line 25: UNIQUE constraint failed: Settings.key
Error: near line 26: UNIQUE constraint failed: Settings.key
Error: near line 27: UNIQUE constraint failed: Settings.key
Error: near line 28: UNIQUE constraint failed: Settings.key
Error: near line 29: UNIQUE constraint failed: Settings.key
Error: near line 30: UNIQUE constraint failed: Settings.key
Error: near line 31: UNIQUE constraint failed: Settings.key
Error: near line 32: UNIQUE constraint failed: Settings.key
Error: near line 33: UNIQUE constraint failed: Settings.key
Error: near line 34: UNIQUE constraint failed: Settings.key```

**Comment by grantjenks** [comment]
Here's the Settings table:

        sql('CREATE TABLE IF NOT EXISTS Settings ('
            ' key TEXT NOT NULL UNIQUE,'
            ' value)'
        )

What are the key/value pairs in the Settings table?

DiskCache sets pragma synchronous to 1, aka normal, but you could set it to 2, aka full. SQLite docs at https://www.sqlite.org/pragma.html#pragma_synchronous and DiskCache docs at http://www.grantjenks.com/docs/diskcache/tutorial.html#settings

I wonder if there's a bug in some other component... DiskCache memory-maps the first part of the database and that makes it vulnerable to a stray pointer over-writing the database. You could also disable the memory-map feature: https://www.sqlite.org/pragma.html#pragma_mmap_size

**Comment by tachim** [comment]
Hi @grantjenks this was actually my mistake; I had pushed the code and people were concurrently accessing the SQLite database, which is probably where the corruption came from. Either way the database was recoverable so no big deal.
