### ISSUE TITLE
improper sql escape

### ISSUE THREAD

**Issue by tachim** [grantjenks/python-diskcache#68]
https://github.com/grantjenks/python-diskcache/blob/70b320b4803d6ad1159d42ba99712529023b2114/diskcache/core.py#L1888

This will cause an operational error: `OperationalError: near "-": syntax error` if the value has a dash in it.

**Comment by tachim** [comment]
Also doesn't seem that smart to retry *60000 times*...

**Comment by grantjenks** [comment]
Good point ... but What pragma value has a dash in it?

**Comment by grantjenks** [comment]
The 60000 retry is for a full minute. It sleeps for one millisecond on error. On slow CIs it can be a real issue with many processes starting simultaneously.
