### ISSUE TITLE
Disk I/O Error, unable to write db

### ISSUE THREAD

**Issue by sekkit** [grantjenks/python-diskcache#69]
File "/media/psf/AllFiles/Volumes/OSXStorage/lacg/trunk/server/src/assets/scripts/base/Avatar.py", line 211, in onTimer
    self.update()
   S_ERR    baseapp01 0 6129652375332859700  [2018-04-14 20:48:30 581] -   File "/media/psf/AllFiles/Volumes/OSXStorage/lacg/trunk/server/src/assets/scripts/base/Avatar.py", line 197, in update
    invoke_components(self, '_on_update')
   S_ERR    baseapp01 0 6129652375332859700  [2018-04-14 20:48:30 582] -   File "/media/psf/AllFiles/Volumes/OSXStorage/lacg/trunk/server/src/assets/scripts/base/Avatar.py", line 37, in invoke_components
    getattr(basecls, method)(self, *args)
   S_ERR    baseapp01 0 6129652375332859700  [2018-04-14 20:48:30 582] -   File "/media/psf/AllFiles/Volumes/OSXStorage/lacg/trunk/server/src/assets/scripts/umodule/debug_module.py", line 52, in _on_update
    cache.write_cache(self.user.uid, server_util.pickle(self.user.pack_to_dict()))
   S_ERR    baseapp01 0 6129652375332859700  [2018-04-14 20:48:30 583] -   File "/media/psf/AllFiles/Volumes/OSXStorage/lacg/trunk/server/src/assets/scripts/common/cache.py", line 7, in write_cache
    with Cache(os.getenv('LACG_CACHE_PATH')) as cache:
   S_ERR    baseapp01 0 6129652375332859700  [2018-04-14 20:48:30 583] -   File "/media/psf/AllFiles/Volumes/OSXStorage/lacg/trunk/server/src/assets/scripts/libs/diskcache/core.py", line 418, in __init__
    sql('CREATE TABLE IF NOT EXISTS Settings ('
   S_ERR    baseapp01 0 6129652375332859700  [2018-04-14 20:48:30 583] - sqlite3.OperationalError: disk I/O error

**Comment by grantjenks** [comment]
There are lots of potential causes for the error. It’s saying it can’t write to the cache database for whatever reason. That’s more likely an OS/filesystem issue than diskcache/SQLite issue. The place where it’s failing is the first SQL write query that is executed.

Can you describe your filesystem environment? Are you running on an NFS mount or drive? Is it a directory watched by Dropbox or Google Drive? All those services will temporarily lock the file which can make it unwriteable.

One last thing, initializing a cache object is a fairly expensive operation (milliseconds). You probably don’t want to be doing that for every log message. Better to construct the cache object and maintain a reference to it.

**Comment by grantjenks** [comment]
DiskCache is process-safe so multiple processes calling ``set`` simultaneously is supported ✓ and tested. I have it working like that in production though I do not re-create the Cache object every time I want to ``set`` an item.

I can't tell from here what the problem is so some things that might help:
* Do you have some file sharing turned on between OSX and Ubuntu through Parallels? I wonder if that might cause issues?
* Do you have an anti-virus software running on Ubuntu? That may present issues too.
* Is it a permanent state or temporary one? If you retry the write, does it work?
* Can you tun the process under ``strace`` and observe the system calls made by the process? Can you share a trace in the scenario where it fails?

**Comment by sekkit** [comment]
Im testing it and will tell you the result later, thx man.

**Comment by sekkit** [comment]
I still get the error 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 120, in worker
    with dc.Cache(DIRECTORY) as cache:
  File "/media/psf/AllFiles/Volumes/OSXStorage/lacg/trunk/server/src/assets/scripts/libs/diskcache/core.py", line 418, in __init__
    sql('CREATE TABLE IF NOT EXISTS Settings ('
sqlite3.OperationalError: disk I/O error

In mac os, it works fine. In ubuntu, first time it'll through disk IO error

**Comment by grantjenks** [comment]
I can run it on an Ubuntu server in Google Cloud without error. I’m afraid parallels may be doing something not exactly POSIX-compliant. Since it fails reliably, can you try running strace? There’s a good article about it at https://www.tecmint.com/strace-commands-for-troubleshooting-and-debugging-linux/

I would also modify the test script and remove the multiproocessing. Simply have the test script loop forever, opening and writing a key in the cache. Run two copies of that modified script with one under strace and see if you can capture the failure.

**Comment by sekkit** [comment]
thx, gonna try later.

**Comment by sekkit** [comment]
I run strace but no cache file info was found.
I created the cache inside linux disk instead of shared mac disk, then it works.
It seems the file has some permission issues or the parallels tool's problem.
I am glad pydiskcache is functional and I will try to use it in my project.
Thanks for your brilliant work, and your advice.

**Comment by sekkit** [comment]
execve("/bin/df", ["df", "-h"], [/* 66 vars */]) = 0
brk(NULL)                               = 0x9cf000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=94080, ...}) = 0
mmap(NULL, 94080, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f9629e16000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1868984, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9629e15000
mmap(NULL, 3971488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f962983e000
mprotect(0x7f96299fe000, 2097152, PROT_NONE) = 0
mmap(0x7f9629bfe000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7f9629bfe000
mmap(0x7f9629c04000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f9629c04000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9629e14000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9629e13000
arch_prctl(ARCH_SET_FS, 0x7f9629e14700) = 0
mprotect(0x7f9629bfe000, 16384, PROT_READ) = 0
mprotect(0x616000, 4096, PROT_READ)     = 0
mprotect(0x7f9629e2d000, 4096, PROT_READ) = 0
munmap(0x7f9629e16000, 94080)           = 0
brk(NULL)                               = 0x9cf000
brk(0x9f0000)                           = 0x9f0000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2981280, ...}) = 0
mmap(NULL, 2981280, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f9629566000
close(3)                                = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2995, ...}) = 0
read(3, "# Locale name alias data base.\n#"..., 4096) = 2995
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/usr/share/locale/en_US/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=619, ...}) = 0
mmap(NULL, 619, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f9629e2c000
close(3)                                = 0
open("/proc/self/mountinfo", O_RDONLY)  = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "22 27 0:21 / /sys rw,nosuid,node"..., 1024) = 1024
read(3, "s-agent,name=systemd\n33 22 0:28 "..., 1024) = 1024
read(3, "relatime shared:21 - cgroup cgro"..., 1024) = 1024
read(3, "ared:152 - prl_fs Home rw,sync\n1"..., 1024) = 619
read(3, "", 1024)                       = 0
lseek(3, 0, SEEK_CUR)                   = 3691
close(3)                                = 0
stat("/sys", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/proc", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/dev", {st_mode=S_IFDIR|0755, st_size=3980, ...}) = 0
stat("/dev/pts", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/run", {st_mode=S_IFDIR|0755, st_size=880, ...}) = 0
stat("/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/sys/kernel/security", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/dev/shm", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=200, ...}) = 0
stat("/run/lock", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=100, ...}) = 0
stat("/sys/fs/cgroup", {st_mode=S_IFDIR|0755, st_size=360, ...}) = 0
stat("/sys/fs/cgroup/systemd", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/pstore", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/devices", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/blkio", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/hugetlb", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/net_cls,net_prio", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/pids", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/cpuset", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/memory", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/cpu,cpuacct", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/perf_event", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/rdma", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/sys/fs/cgroup/freezer", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
stat("/proc/sys/fs/binfmt_misc", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/dev/mqueue", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=40, ...}) = 0
stat("/sys/kernel/debug", {st_mode=S_IFDIR|0700, st_size=0, ...}) = 0
stat("/dev/hugepages", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/sys/kernel/config", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/sys/fs/fuse/connections", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/proc/sys/fs/binfmt_misc", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/media/psf/AllFiles", {st_mode=S_IFDIR|0755, st_size=1496, ...}) = 0
stat("/media/psf/Home", {st_mode=S_IFDIR|0755, st_size=3536, ...}) = 0
stat("/media/psf/lacg", {st_mode=S_IFDIR|0755, st_size=238, ...}) = 0
stat("/media/psf/db", {st_mode=S_IFDIR|0755, st_size=136, ...}) = 0
stat("/run/user/1000", {st_mode=S_IFDIR|0700, st_size=260, ...}) = 0
stat("/run/user/1000/gvfs", {st_mode=S_IFDIR|0500, st_size=0, ...}) = 0
stat("/media/sekkit/CDROM", {st_mode=S_IFDIR|0500, st_size=2048, ...}) = 0
uname({sysname="Linux", nodename="ubuntu", ...}) = 0
statfs("/dev", {f_type="TMPFS_MAGIC", f_bsize=4096, f_blocks=1013805, f_bfree=1013805, f_bavail=1013805, f_files=1013805, f_ffree=1013360, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4130}) = 0
statfs("/run", {f_type="TMPFS_MAGIC", f_bsize=4096, f_blocks=204079, f_bfree=201740, f_bavail=201740, f_files=1020393, f_ffree=1019770, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4138}) = 0
statfs("/", {f_type="EXT2_SUPER_MAGIC", f_bsize=4096, f_blocks=16222927, f_bfree=13752693, f_bavail=12922857, f_files=4128768, f_ffree=3584491, f_fsid={880248906, 1140021385}, f_namelen=255, f_frsize=4096, f_flags=4128}) = 0
statfs("/sys/kernel/security", {f_type="SECURITYFS_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/dev/shm", {f_type="TMPFS_MAGIC", f_bsize=4096, f_blocks=1020393, f_bfree=1020330, f_bavail=1020330, f_files=1020393, f_ffree=1020384, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=38}) = 0
statfs("/run/lock", {f_type="TMPFS_MAGIC", f_bsize=4096, f_blocks=1280, f_bfree=1279, f_bavail=1279, f_files=1020393, f_ffree=1020387, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup", {f_type="TMPFS_MAGIC", f_bsize=4096, f_blocks=1020393, f_bfree=1020393, f_bavail=1020393, f_files=1020393, f_ffree=1020376, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=47}) = 0
statfs("/sys/fs/cgroup/systemd", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/pstore", {f_type="PSTOREFS_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/devices", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/blkio", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/hugetlb", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/net_cls,net_prio", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/pids", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/cpuset", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/memory", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/cpu,cpuacct", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/perf_event", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/rdma", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/sys/fs/cgroup/freezer", {f_type="CGROUP_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4142}) = 0
statfs("/proc/sys/fs/binfmt_misc", {f_type="BINFMTFS_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4128}) = 0
statfs("/dev/hugepages", {f_type="HUGETLBFS_MAGIC", f_bsize=2097152, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=2097152, f_flags=4128}) = 0
statfs("/sys/kernel/config", {f_type=0x62656570, f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4128}) = 0
statfs("/media/psf/AllFiles", {f_type=0x7c7c6673, f_bsize=4096, f_blocks=127991444, f_bfree=33994437, f_bavail=33994437, f_files=4096, f_ffree=4096, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=1078}) = 0
statfs("/media/psf/Home", {f_type=0x7c7c6673, f_bsize=4096, f_blocks=127991444, f_bfree=33994437, f_bavail=33994437, f_files=4096, f_ffree=4096, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=1078}) = 0
statfs("/media/psf/lacg", {f_type=0x7c7c6673, f_bsize=4096, f_blocks=58497937, f_bfree=5642391, f_bavail=5642391, f_files=4096, f_ffree=4096, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=1078}) = 0
statfs("/media/psf/db", {f_type=0x7c7c6673, f_bsize=4096, f_blocks=58497937, f_bfree=5642391, f_bavail=5642391, f_files=4096, f_ffree=4096, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=1078}) = 0
statfs("/run/user/1000", {f_type="TMPFS_MAGIC", f_bsize=4096, f_blocks=204079, f_bfree=204046, f_bavail=204046, f_files=1020393, f_ffree=1020345, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4134}) = 0
statfs("/run/user/1000/gvfs", {f_type=0x65735546, f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=1024, f_frsize=4096, f_flags=4134}) = 0
statfs("/media/sekkit/CDROM", {f_type="ISOFS_SUPER_MAGIC", f_bsize=2048, f_blocks=50880, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={2816, 0}, f_namelen=255, f_frsize=2048, f_flags=4135}) = 0
open("/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=26258, ...}) = 0
mmap(NULL, 26258, PROT_READ, MAP_SHARED, 3, 0) = 0x7f9629e25000
close(3)                                = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 21), ...}) = 0
write(1, "Filesystem      Size  Used Avail"..., 49Filesystem      Size  Used Avail Use% Mounted on
) = 49
write(1, "udev            3.9G     0  3.9G"..., 43udev            3.9G     0  3.9G   0% /dev
) = 43
write(1, "tmpfs           798M  9.2M  789M"..., 43tmpfs           798M  9.2M  789M   2% /run
) = 43
write(1, "/dev/sda1        62G  9.5G   50G"..., 40/dev/sda1        62G  9.5G   50G  17% /
) = 40
write(1, "tmpfs           3.9G  252K  3.9G"..., 47tmpfs           3.9G  252K  3.9G   1% /dev/shm
) = 47
write(1, "tmpfs           5.0M  4.0K  5.0M"..., 48tmpfs           5.0M  4.0K  5.0M   1% /run/lock
) = 48
write(1, "tmpfs           3.9G     0  3.9G"..., 53tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
) = 53
write(1, "AllFiles        489G  359G  130G"..., 58AllFiles        489G  359G  130G  74% /media/psf/AllFiles
) = 58
write(1, "Home            489G  359G  130G"..., 54Home            489G  359G  130G  74% /media/psf/Home
) = 54
write(1, "lacg            224G  202G   22G"..., 54lacg            224G  202G   22G  91% /media/psf/lacg
) = 54
write(1, "db              224G  202G   22G"..., 52db              224G  202G   22G  91% /media/psf/db
) = 52
write(1, "tmpfs           798M  132K  798M"..., 53tmpfs           798M  132K  798M   1% /run/user/1000
) = 53
write(1, "/dev/sr0        100M  100M     0"..., 58/dev/sr0        100M  100M     0 100% /media/sekkit/CDROM
) = 58
close(1)                                = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by grantjenks** [comment]
Ok, it sounds like Parallels is getting in the way. Whatever it does to sink the files between between VM and macOS must temporarily lock the file in such a way that it causes the disk I/O error.

You will have to run diskcache on a Linux VM disk not managed my Parallels. Sorry for that! But glad you found a work-around.

Also, thanks for your kind words.

**Comment by grantjenks** [comment]
Add note to Tutorial/Caveats section about Parallels shared folders at 3b9dfbf
