### ISSUE TITLE
Why is culling slow for Django core's filebased cache?

### ISSUE THREAD

**Issue by ckcollab** [grantjenks/python-diskcache#7]
First of all thanks for releasing this! Super cool library, I was just reading about your benchmarks and wondering why culling (glob) was needed (and why it's slow)? The reason you "cull" is to check if you need to remove some old keys to make space for some new `set()`, is that right?

Would it be possible to keep track of old file state somehow instead of having to keep globbing? Or making many smaller folders to make the sets cheaper... not sure I understand how all this works, and I'm sure you've thought of this I'm just curious why it's not the way-to-go. Thanks for any explanation, I hope to use this on some fun projects soon :)

**Comment by grantjenks** [comment]
You've got it. The Django core filebased cache backend tries to *cull* on each *set*. The *cull* operation uses *glob* and that's slow. Getting a list of all files in the directory seems to scale linearly with the number of files in the directory. Here's the source:

* [Django filebased backend source](https://github.com/django/django/blob/master/django/core/cache/backends/filebased.py#L48)
* [Python 2.7 glob.glob1 source](https://github.com/python/cpython/blob/2.7/Lib/glob.py#L71)

I thought of a few different designs but settled here. There are some clever things you could do with the filesystem but I chose to use SQLite to maintain things.

There's a Django bug report at https://code.djangoproject.com/ticket/11260 but it was closed Won't Fix. I think most people who stick with filebased caching end up using a cron job to expire items. This still has the drawback that it works randomly.

Note that you can set `cull_limit` to 0 in DiskCache to disable culling. A cron job could then expire files outside the request/response cycle.

**Comment by ckcollab** [comment]
> Note that you can set cull_limit to 0 in DiskCache to disable culling. A cron job could then expire files outside the request/response cycle.

Ah.. that makes tons of sense. Thanks for the quick reply!
