### ISSUE TITLE
SQLite Memory error on MacOSX when using diskcache with Processes

### ISSUE THREAD

**Issue by braybaud** [grantjenks/python-diskcache#75]
When using diskcache on MacOSX High Sierra (10.13.8) within `Process`, the program fails with the following error:
```
Process CacheProc-4:
Traceback (most recent call last):
  File "/Users/dev/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "cache_mp_test.py", line 15, in run
    self.cache.append("test")
  File ".../python-diskcache/diskcache/persistent.py", line 349, in append
    _cache_push(value)
  File ".../python-diskcache/diskcache/core.py", line 1215, in push
    with self._transact(filename) as (sql, cleanup):
  File ".../.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File ".../python-diskcache/diskcache/core.py", line 574, in _transact
    sql('BEGIN IMMEDIATE')
MemoryError
```
This error is also encountered when running the tests using multiprocessing like:
- `stress_test_deque_mp.py`
- `stress_test_index_mp.py`

Here is a quick program for easy repro:
``` python
from multiprocessing import Process
from diskcache import Deque

class CacheProc(Process):
    def __init__(self, cache):
        super().__init__()
        self.cache = cache

    def run(self):
        self.cache.append("test")

if __name__ == "__main__":
    cache = Deque(directory='/temp')
    procs = []
    for _ in range(10):
        p = CacheProc(cache)
        procs.append(p)
        p.start()

    for p in procs:
        p.join()
```

**Comment by grantjenks** [comment]
Are you running low on memory?

I can't reproduce with your test script. I can also run both stress tests and they pass.

MemoryError is an odd an exception to see here. Have you configured Disk Cache to memory map a large segment of memory?

**Comment by braybaud** [comment]
Im not low on memory and was able to reproduce the issue on both my MacBook Pro and Mac pro.

The following code works fine:

```python
from multiprocessing import Process

from diskcache import Deque

class CacheProc(Process):
    def run(self):
        self.cache = Deque(directory='/temp')
        self.cache.append("test")

if __name__ == "__main__":
    procs = []
    for _ in range(10):
        p = CacheProc()
        procs.append(p)
        p.start()

    for p in procs:
        p.join()
```
Looks like the error only occurs when passing the cache.
Also creating the cache in the `__init__` of the `CacheProc` leads to the same error...

**Comment by grantjenks** [comment]
Cache objects do not survive forking because file handles are used to connect to the SQLite database. Are you sure the instance objects of Process are serialized using pickle before/after the run() method is called?

**Comment by grantjenks** [comment]
I did some experiments locally and observed two things:

1. I can't reproduce the error as you can. I also have a MacBook Pro with MacOS v10.13.6 but it works without issue. I installed Python from MacPorts so maybe there's different compilation flags at work.

2. When using multiprocessing on MacOS, the preferred "start method" is to fork which does not use the reliable pickle/unpickle technique. If you switch to using the "[spawn](https://docs.python.org/3.6/library/multiprocessing.html#contexts-and-start-methods)" start method then I believe it will work.

The most reliable way to work around the problem will be to simply create the Deque object in the process manually using the path to the directory.

**Comment by braybaud** [comment]
Thanks a lot @grantjenks for your pointers. Ill experiment with the better MacOS approach and hopefully get some luck there 👍

**Comment by braybaud** [comment]
Switching to spawn worked on MacOS:
``` python 
import multiprocessing as mp
mp.set_start_method("spawn")
```
