### ISSUE TITLE
DiskCache file size discrepancies between versions

### ISSUE THREAD

**Issue by bertji** [grantjenks/python-diskcache#79]
I've been using diskcache 2.9.0 for a while and recently upgraded to 3.0.x.  It seems like there is a big discrepancy in the size of the files between the 2.9.0 and 3.0.x versions.  

Below cache directories should contain exactly the same data but have drastically different sizes
![image](https://user-images.githubusercontent.com/1683378/45894469-d0ca3880-bda4-11e8-8dcf-d9a29f6d858f.png)

![image](https://user-images.githubusercontent.com/1683378/45894495-e17aae80-bda4-11e8-8bd1-e81b01dd37d0.png)

Any idea why this might be happening?

**Comment by bertji** [comment]
Let me see if I can reduce the problem to a manageable/replicatable size...

**Comment by grantjenks** [comment]
Hi @bertji, did you have any luck reproducing the problem?

**Comment by bertji** [comment]
Ah sorry! I got distracted! Let me generate some test code today and post
an update here.

**Comment by bertji** [comment]
Looks like when I use the code below to create a fresh diskcache and populate it with the same random data, the number of files and size roughly match between the two versions (2.9.0 and 3.0.6).  I also tried to re-load the same data to see if either version was going to duplicate the data and it didn't.  At this point, it must have been something in my code that was duplicating data.  I'll have to inspect it further, but I'll close this issue since it has been verified it behaves as expected.

Sorry about the noise!

```
import pandas as pd
import numpy as np
import random
import os
import diskcache

# Generate Staged Files
stage_dir_path = 'E:\diskcache_stage'
if not os.path.exists(stage_dir_path):
    os.mkdir(stage_dir_path)
for _ in range(50):
    file_id = '{}-10-A'.format(np.random.randint(1000, 9999))
    sample_df =\
        pd.concat([
            pd.Series(np.random.randint(1, 100000, 50000), name='A'),
            pd.Series(np.random.randint(1, 10000, 50000), name='B'),
            pd.Series(np.random.randint(1, 365, 50000), name='C'),
            pd.Series(np.random.random(50000), name='D'),
            pd.Series(np.random.random(50000), name='E')], axis=1)
    sample_df.to_csv(os.path.join(stage_dir_path, '{}.csv'.format(file_id)))

# Create DiskCache
dcache_dir = r'E:\temp_cache_2_9_0'
with diskcache.Cache(dcache_dir, size_limit=5e+9) as dcache:
    dcache_db_path = os.path.join(dcache_dir, 'cache.db')
    if os.path.exists(dcache_db_path):
        print(True)
    else:
        print(False)

# Load DiskCache
with diskcache.Cache(dcache_dir) as dcache:
    for file_name in os.listdir(stage_dir_path):
        file_path = os.path.join(stage_dir_path, file_name)
        sample_df = pd.read_csv(file_path, index_col=0)
        cache_key = file_name.split('.')[0].encode('utf-8')
        dcache.add(cache_key, sample_df)
```
