### ISSUE TITLE
Add "Dummy" FanoutCache with same interface but no caching

### ISSUE THREAD

**Issue by impredicative** [grantjenks/python-diskcache#81]
It would help to have a flag that temporarily disables an instance of `FanoutCache`. Sometimes I don't want the cache enabled when I'm testing. I should for example be able to do:

```python
_CACHE = diskcache.FanoutCache('\my\cache', shards=4, timeout=2)

if __name__ == '__main__':
    _CACHE.enabled = False
   test_without_cache()
   _CACHE.enabled = True  # default
   test_with_cache()
```

**Comment by grantjenks** [comment]
What’s the behavior of the cache when enable is False?

**Comment by impredicative** [comment]
The requested behavior is a simple passthrough. Nothing gets retrieved from the cache, and nothing gets set into the cache.

**Comment by grantjenks** [comment]
I don’t like the “enabled” attribute much but I would be open to a DummyFanoutCache type. I’ve seen that in Django and it makes sense for testing.

**Comment by impredicative** [comment]
That's fine. I can initialize either `FanoutCache` or `DummyFanoutCache` based on a True/False state variable.

**Comment by grantjenks** [comment]
I think you would do something like:

```python
CACHE = diskcache.FanoutCache('path/to/your/cache', shards=4, timeout=2)

if __name__ == '__main__':
    CACHE = diskcache.DummyFanoutCache()
```

I would expect DummyFanoutCache to have an identical API (even down to the `__init__` params like `directory` and `shards` though they would do nothing).

I'm still not exactly sure what some methods should return. I wonder if you could approximate what you want by setting the cache size limit to zero? That wouldn't be as fast as a dummy cache but it may have better semantics.

In any case, I'm not likely to work on this but I would consider a pull request. It may help to fully and precisely describe what you want.

**Comment by grantjenks** [comment]
One more thought here, the FanoutCache uses core.Cache in shards. Maybe a dummy cache version of core.Cache would be better.

**Comment by grantjenks** [comment]
@impredicative if you get something that works well then pull request welcome.
