### ISSUE TITLE
Better Feature Comparison to Promote Index and Deque more

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/python-diskcache#82]
I need to do more to promote diskcache.Index and diskcache.Deque. Good to do some feature comparisons with:

* ZODB -- http://www.zodb.org/en/latest/
* ldtable -- https://github.com/Jwink3101/ldtable (has benchmarks!)
* klepto -- https://pypi.org/project/klepto/
* dataset -- https://dataset.readthedocs.io/en/latest/quickstart.html
* buzhug -- http://buzhug.sourceforge.net/
* sqlitedict -- https://github.com/RaRe-Technologies/sqlitedict
* pickleDB -- https://pythonhosted.org/pickleDB/index.html
* shelve -- https://docs.python.org/3/library/shelve.html
* TinyDB -- https://tinydb.readthedocs.io/en/latest/
* CodernityDB -- http://labs.codernity.com/codernitydb/
  * Benchmarks: http://labs.codernity.com/codernitydb/speed.html
* sqlite3 -- https://docs.python.org/3/library/sqlite3.html
* redis -- https://redis.io/clients#python
* gadfly -- http://gadfly.sourceforge.net/
* KirbyBase -- https://pypi.org/project/KirbyBase/
* dbm -- https://docs.python.org/3/library/dbm.html
* joblib.Memory -- https://joblib.readthedocs.io/en/latest/index.html
* SQLAlchemy -- https://www.sqlalchemy.org/
* MongoDB -- https://api.mongodb.com/python/
* pandas

**Comment by aoyal** [comment]
Interested in a comparision with klepto.

**Comment by aoyal** [comment]
Any updates on this?

**Comment by grantjenks** [comment]
Nope. Pull request welcome.

**Comment by grantjenks** [comment]
Features

* Persistent? Yes/No
* Thread-safe? Yes/No
* Process-safe? Yes/No
* Backend? Memory/Filesystem/SQLite/Redis/SQLAlchemy/etc.
* Docs? None/Readme/Extensive
* Tests? Yes/No
* Coverage? Yes/No
* Stress? Yes/No
* Serialization? Pickle/JSON/etc.
* Benchmarks? get/set/delete
* Atomic? Yes/No
* Data Types? Mapping (Ordered, Sorted)/Deque/etc.
* Vacuum? Automatic/Manual
* Python? 2/3/etc.
* CI Tests? None/Travis/AppVeyor/etc.
* Sources? GitHub/SourceForge

**Comment by grantjenks** [comment]
Created pull request #88 

Need to feature Index and Deque data types more prominently.

**Comment by grantjenks** [comment]
Fixed at 024c4d9
