### ISSUE TITLE
flask-cache is unmaintain - new repo flask-caching

### ISSUE THREAD

**Issue by alochym01** [grantjenks/python-diskcache#83]
is there any road map to support flask-caching
https://github.com/sh4nks/flask-caching

thank you

**Comment by grantjenks** [comment]
I’m aware of it but don’t intend to implement support soon/myself. It’s listed under Requests for Contributions on the project Development page: http://www.grantjenks.com/docs/diskcache/development.html

Short version: Pull request welcome :)

I am also open to contracting for features.

**Comment by grantjenks** [comment]
I updated the development page to reference Flask-Caching at 6511693
