### ISSUE TITLE
Add Memoizing Decorator Support

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/python-diskcache#9]
As described in [DiskCache Development](http://www.grantjenks.com/docs/diskcache/development.html#requests-for-contributions) it would be great to have an lru_cache-like decorator to cache function calls.

I contacted Yuval Greenfield, the author of [filecache](https://pypi.python.org/pypi/filecache) and he said the missing decorator feature was what blocked him from using the module. His decorator accepts one argument, seconds before expiry.

I prototyped something simple in [Issue #8](https://github.com/grantjenks/python-diskcache/issues/8#issuecomment-202229221). It should be relatively easy to combine it with the source from [Python 3's functools.lru_cache](https://hg.python.org/cpython/file/3.5/Lib/functools.py#l340)

**Comment by grantjenks** [comment]
Example: http://funcy.readthedocs.io/en/stable/calc.html#memoize

**Comment by grantjenks** [comment]
Needs "typed=False" parameter. See: https://bugs.python.org/issue13227

**Comment by tamirOK** [comment]
@grantjenks , does decorator have to store cached data on disk?

**Comment by grantjenks** [comment]
Yes, I would expect it to use ``core.Cache`` internally.

**Comment by grantjenks** [comment]
Deployed at 2.8.2

The new feature is at FanoutCache.memoize and DjangoCache.memoize
