### ISSUE TITLE
Can you consider linking relevant Django bugs?

### ISSUE THREAD

**Issue by matkoniecz** [grantjenks/python-diskcache#93]
On reading

> Unfortunately the file-based cache in Django is essentially broken.

my first impulse is to report bug on a Django bug tracker. Second impulse is to start checking whatever this issue is already reported. Can you consider linking relevant reported bugs so that it is not necessary for everybody to do in on their own?

If you would accept a PR - let me know and I will locate relevant issues and make a PR linking them.

**Comment by grantjenks** [comment]
It's not broken in a "buggy" sense. It's broken in a "does not scale" sense. The next two lines explain:

> The culling method is random and large caches repeatedly scan a cache directory which slows linearly with growth. Can you really allow it to take sixty milliseconds to store a key in a cache with a thousand items?

The DjangoCache benchmarks elaborate: http://www.grantjenks.com/docs/diskcache/djangocache-benchmarks.html#filebased

If you can find a bug number, then I would consider linking to it. But I think the ambiguity of my phrasing has maybe confused you.

Pull requests are always welcome.

**Comment by matkoniecz** [comment]
If it is scaling very poorly then I would expect that somebody created bug report/feature request proposing to improve that situation.

For now I found documentation of caches at https://docs.djangoproject.com/en/2.1/topics/cache/#filesystem-caching

It seems to be used very rarely given low bug report count at https://code.djangoproject.com/query?status=assigned&status=closed&status=new&summary=~FileBasedCache&desc=1&order=id

Have you considered reporting performance issues in FileBasedCache? (like people did with some bugs form https://code.djangoproject.com/query?status=assigned&status=closed&status=new&summary=~performance&desc=1&order=id list)

**Comment by thinkwelltwd** [comment]
@matkoniecz cut the man a break!! It's not @grantjenks job to push and pull FileBasedCache to fit his requirements. The deficiencies of FileBasedCache are too well known to require enumeration, or to merit reproving the author of a caching library that's compatible with, but not dependent on Django.

**Comment by matkoniecz** [comment]
To make it explicit: I am not considering it as @grantjenks job/duty/obligation/whatever to improve/use/report issues in Django.

I am mostly trying to confirm that Django is actually deficient (and it is not for example case of outdated docs), as I am not an expert in Django caching.

> The deficiencies of FileBasedCache are too well known to require enumeration

Well, for example I was unaware about this problem and I would prefer to not discover it on my own - that is why I want to at least open a Django issue.

**Comment by matkoniecz** [comment]
I created https://code.djangoproject.com/ticket/29994#ticket
