### ISSUE TITLE
consider adding minimal usage example in readme

### ISSUE THREAD

**Issue by matkoniecz** [grantjenks/python-diskcache#94]
it is always nice to have starting code that allows to quickly start

it also allows to make a quick test that library/computer/OS is not completely borked and at least the simples usecase works

**Comment by grantjenks** [comment]
The tutorial seems pretty comprehensive to me: http://www.grantjenks.com/docs/diskcache/tutorial.html

What's missing?

**Comment by matkoniecz** [comment]
> What's missing?

I would not say that things are missing (in fact tutorial is a really good one), but at least I like to have in readme some short code that presents one of simplest usecases.

In my case I made 

```
from diskcache import Cache 
cache = Cache('tmp/mycachedir')
print(len(cache))
cache.set(b'key', b'value')
print(cache.get(b'key'))
del cache[b'key']
print(cache.get(b'key'))
cache.add(b'testX', 123)
cache.add([1,[2]], "less usual types")
cache.add([1,[2],[3]], ["less usual types",[1234]])
print(cache.get([1,[2]]))
print(cache.get([1,[2],[3]]))
print(len(cache))
cache.close()
```

I thought about making (a bit less messy) version and adding it at https://github.com/grantjenks/python-diskcache#quickstart

**Comment by grantjenks** [comment]
I would rather you not add that in the Quickstart. I prefer to force people to read (or at least skim) the tutorial. Also, the top of the readme includes a micro-benchmark with the simplest get/set operations.

**Comment by matkoniecz** [comment]
OK, in that case I am closing
