### ISSUE TITLE
Django Settings: TIMEOUT vs DATABASE_TIMEOUT

### ISSUE THREAD

**Issue by raratiru** [grantjenks/python-diskcache#97]
I got confused from the `DATABASE_TIMEOUT` setting that appears in the [DiskCache docs](http://www.grantjenks.com/docs/diskcache/tutorial.html#djangocache), vs the `TIMEOUT` setting used in the [django settings](https://docs.djangoproject.com/en/dev/topics/cache/#cache-arguments).

Looking at the source:

https://github.com/grantjenks/python-diskcache/blob/2e3af05c435023213353fa6084252059b03acd92/diskcache/djangocache.py#L25-L28

I understand that the following configuration is more clear and I would like to verify it:

```
CACHES = {
    'default': {
        'BACKEND': 'diskcache.DjangoCache',
        'LOCATION': '/path/to/cache/directory',
        'SHARDS': 4,
        'DATABASE_TIMEOUT': 1.0,  # Timeout for each DjangoCache database transaction
        'TIMEOUT': 300,  # Default timeout for each key
        'OPTIONS': {
            'size_limit': 2 ** 32  # 4 gigabytes
        },
    },
}

```

**Comment by grantjenks** [comment]
Yes, that's correct.

**Comment by raratiru** [comment]
Thank you, I created a pr that reflects the above.
